### ISSUE TITLE
Bug: Hover suggestions don't include documatic description if description begins with html tag

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/language-server#100]
If a documatic description (i.e. /// comment) begins with an HTML tag (such as \<p\>), then the hover text does not the display the description. This can be seen with methods such as $System.Mirror.IsPrimary(). Here is a reference to the method:

<img width="347" alt=" 2020-12-10 at 16 16 32" src="https://user-images.githubusercontent.com/75783557/101762621-aa1e8680-3b03-11eb-85af-b5aab7c244d5.png">

And here is the method definition (and description):

<img width="503" alt=" 2020-12-10 at 16 16 44" src="https://user-images.githubusercontent.com/75783557/101762670-b99dcf80-3b03-11eb-925f-1daa78e97268.png">

I am using v1.0.5 on a Mac.

**Comment by isc-bsaviano** [comment]
@isc-kiyer The HTML is being stripped because the VSCode client thinks that the documentation text is Markdown. However, the lines that don't contain HTML should be left intact. I will investigate.

**Comment by isc-bsaviano** [comment]
To resolve this issue I'm going to import turndown, an npm package that will convert the HTML tags in the class reference to Markdown that the VSCode client can understand
