### ISSUE TITLE
If a class contains a property and a method with the same name, code completion only proposes the property

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#105]
Create a class with a property Name and a method Name(). In another **instance** method Test(), type `..N` to trigger code completion. Only the Name property is proposed. If you type the complete property name and then type the left parenthesis, the method is correctly proposed.

**Comment by isc-bsaviano** [comment]
[InterSystems documentation](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GOBJ_classes#GOBJ_classes_naming_membernames) strongly recommends against doing this so the Language Server won't be supporting it.

**Comment by isc-solon** [comment]
I don't think I ever saw that warning before. I concur!
