### ISSUE TITLE
Activate color theme for workspace only

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#109]
At this line

https://github.com/intersystems/language-server/blob/6e37139fefb8916e79382dfb25f30f1a8318c364/client/src/extension.ts#L100

and its dark-theme partner

https://github.com/intersystems/language-server/blob/6e37139fefb8916e79382dfb25f30f1a8318c364/client/src/extension.ts#L117

I propose we set the third parameter `false` so the theme change only gets applied to my current workspace instead of globally. I can still set one of the InterSystems themes globally if I wish (e.g. off VS Code's lower-left gearwheel context menu), in which case I won't get prompted for every new workspace. But if I prefer to use a non-InterSystems theme as my global default this dialog will let me set a better per-workspace theme if I am using the language server extension.

Alternatively, add an extra button to the dialog ("Always"?) that sets it with `true` as the third parameter.

**Comment by gjsjohnmurray** [comment]
I don't know of a way to change its size. How about simplifying the button labels to "Globally", "This Workspace", "Later", "Never" ?

**Comment by isc-bsaviano** [comment]
Those options fit in the normal window. I'll also change the message to "InterSystems recommends that you activate the default dark/light theme" to make more sense with the shortened message

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Jamie and I decided to clean up the message a bit and only use 3 buttons: "Globally", "Only This Workspace" and "Don't Ask Again". Sending you a beta vsix now
