### ISSUE TITLE
Parsing problem with $system.SQL

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#112]
The command If $SYSTEM.SQL.Util.GetMapSelectability(... underlines SQL as a syntax error

**Comment by isc-bsaviano** [comment]
@isc-AndrewCheshire Looks like this new syntax was introduced in 2020.3:

> The configuration and utility functions in $SYSTEM.SQL have now been organized thematically in subclasses such as %SYSTEM.SQL.Functions, %SYSTEM.SQL.Schema and %SYSTEM.SQL.Stats.Runtime, making their signature and behavior more consistent across the board. The old entry points in %SYSTEM.SQL have been deprecated but are still available for backwards compatibility.



Source: https://docs.intersystems.com/iris20203/csp/docbook/Doc.View.cls?KEY=GCRN_new20203#GCRN_new_other
