### ISSUE TITLE
List of suggestions for argument datatypes for a class query is incomplete

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#116]
Add a class query to a class:
`Query Test(arg as %`
If you type `%Str` or `%Int` or `%Dat` you are **not** presented with %String, %Integer, or %Date. If you type `%Library.` you are **not** presented with all the %Library classes. The list of suggestions is incomplete. I think it should be the same as the list for method arguments. Somewhat related to #64.

**Comment by isc-bsaviano** [comment]
Caused by #102
