### ISSUE TITLE
Theme suggestion dialog should not offer workspace option when no workspace is open

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#117]
Start a new VS Code window that doesn't use an InterSystems theme. Open a file (not a folder or a workspace). Set the file's language mode to ObjectScript. Dialog proposing the InterSystems theme includes "Only This Workspace" option. That's not applicable in this situation.

Code pointer:
https://github.com/intersystems/language-server/blob/ddbbecc8930aa68dcc90df9632542635845aaac4/client/src/extension.ts#L91-L105

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray What's the best way to test if a workspace is open? `workspace.name !== undefined`?

**Comment by gjsjohnmurray** [comment]
Indeed, the spec at https://code.visualstudio.com/api/references/vscode-api#workspace says of `workspace.name`

> The name of the workspace. `undefined` when no folder has been opened.
