### ISSUE TITLE
Hover documentation for commands and system functions needs more linebreaks

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#118]
See https://github.com/intersystems-community/vscode-objectscript/issues/557

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I can add newlines after each argument but if the description for that argument is long there will still be horizontal scrolling.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano newlines after each argument will be an adequate improvement at this time I think.

**Comment by isc-bsaviano** [comment]
Changed the title to reflect that line breaks are also needed in the documentation for system functions and structured system variables that take multiple arguments.
