### ISSUE TITLE
Extension settings cannot be set per workspace or per language

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#122]
All contributed configuration settings in package.json are defined as `"scope": "application"` which prevents me from setting workspace-specific values.

For each setting that affects an individual document, please change to `"scope": "language-overridable"` so it becomes possible for different root folders in a multi-root workspace to specify a different value for each of the four language IDs that the language server implements (objectscript, objectscript-class, objectscript-macros, objectscript-csp).

If the setting doesn't logically apply at the document (i.e. resource) level, scope it to `window` so it can be set at the workspace level.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I don't think the LSP supports `language-overridable` settings (see https://github.com/microsoft/vscode-languageserver-node/issues/1043). Assuming I'm correct and that issue doesn't resolves quickly, I think I should use `resource` scoping instead for settings that apply at the document level.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Now that the linked issue has been looked at, I'm going to move forward with `resource` scoping. I don't think `language-overridable` adds any value and it would require some custom middleware code

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano fair enough.
