### ISSUE TITLE
Goto definition fails with server:namespace definition

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#124]
object script issue https://github.com/intersystems-community/vscode-objectscript/issues/450 adds isfs://server:namespace option, but using that seems to have affected the goto definition code of language server.

Defining the server with isfs://server/?ns=BUILDDTL resolves the issue

[Trace - 3:24:32 PM] Received response 'textDocument/definition - (4094)' in 328ms. Request failed: Request textDocument/definition failed with message: Invalid URL: isfs://ascension:builddtl/Test/MySuper.cls (-32603).
[Error - 3:24:32 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Invalid URL: isfs://ascension:builddtl/Test/MySuper.cls
  Code: -32603

**Comment by isc-bsaviano** [comment]
The issue occurs when I try to parse the given document URI to replace the path with the path to the file containing the definition. I think the default URL parser considers `isfs://ascension:builddtl/Test/MySuper.cls` invalid because the parser expects a numerical port to follow `ascension`.

**Comment by isc-bsaviano** [comment]
I think I replace my usage of the default URL parser with the vscode.Uri parser by including the [vscode-uri npm module](https://www.npmjs.com/package/vscode-uri). I will try that.

**Comment by gjsjohnmurray** [comment]
@bourette sorry we didn't pick this up before releasing the version of the ObjectScript extension that added the new syntax.

@isc-bsaviano thanks for fixing it so promptly. Will you be doing a new Language Server release soon?

**Comment by bourette** [comment]
@gjsjohnmurray, no worries, I should have reported it, I knew there was a problem, but hadn't spent the time figuring out what was happening.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Version 1.0.7 will be live in a few minutes. We're planning on 1.1.0 coming next week
