### ISSUE TITLE
Diagnostics don't return a code

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#129]
For example, the "Syntax error" message that displays in the VS Code Problems list doesn't convey as much information as the error messages from the corresponding failed compile.

Example MAC routine:
```objectscript
ROUTINE YJM1
YJM1    ;Testing
    nosuch
    write $nosuch
```

Compiler error text:
```
Compilation started on 01/29/2021 10:58:16 with qualifiers 'cuk'
Compiling routine : YJM1.mac
ERROR: YJM1.int(2) #1026: Invalid command : 'nosuch' : Offset:10 [YJM1+1^YJM1]
 TEXT:     nosuch
ERROR: YJM1.int(3) #1032: Invalid special variable : '$nosuch' : Offset:17 [YJM1+2^YJM1]
 TEXT:     write $nosuch
Detected 2 errors during compilation in 0.001s.
ERROR #5475: Error compiling routine: YJM1.  Errors:  
ERROR: YJM1.int(2) #1026: Invalid command : 'nosuch' : Offset:10 [YJM1+1^YJM1]
 TEXT:     nosuch
ERROR: YJM1.int(3) #1032: Invalid special variable : '$nosuch' : Offset:17 [YJM1+2^YJM1]
 TEXT:     write $nosuch
```

Problems lack the error numbers 1026 and 1032
![image](https://user-images.githubusercontent.com/6726799/106267161-2b9bb680-6221-11eb-96fc-d30a9c730d68.png)

Code pointer: https://github.com/intersystems/language-server/blob/4006a706467cfaf33b3bdcd98e7106b960040ca2/server/src/server.ts#L411-L419

Setting the error code into the `code` property of the `Diagnostic` should make it appear in parentheses after the `source` text (InterSystems Language Server), where it will become filterable.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I can check with Andy next week but I'm pretty sure that I don't get that information from the parser.

**Comment by isc-AndrewCheshire** [comment]
@isc-bsaviano You're correct, the colorer doesn't have that information.  It seems to me that you'll have to get the error codes from the compiler output and use the line numbers to merge the compiler+colorer information for each line.

**Comment by gjsjohnmurray** [comment]
So I suggest we leave the Language Server diagnostics as they are. @isc-bsaviano if you agree, go ahead and close this.

Perhaps I'll open an issue on the ObjectScript extension about getting it to use Diagnostics to report compiler errors. Currently it only creates Diagnostics if LS isn't being used.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I agree that the current LS Diagnostics are fine (there's a difference between syntax errors and compiler errors) but I'm not sure that the main extension should be making its own Diagnostics. There will likely be overlaps between compiler error diagnostics and syntax error/class not found diagnostics which might confuse the user.
