### ISSUE TITLE
Provide support for manually triggered completion requests

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#13]
- [ ] As can suggest only when nothing typed.

![image](https://user-images.githubusercontent.com/1212251/95499345-d277f080-09ad-11eb-902e-fd3a025b488f.png)

- [ ] Extends, can suggest when type dot '.' and nothing if something typed

![image](https://user-images.githubusercontent.com/1212251/95499380-de63b280-09ad-11eb-8100-0706a3dbee58.png)

- [x] Does not suggest class members

![image](https://user-images.githubusercontent.com/1212251/95499698-5c27be00-09ae-11eb-905c-f2d49334ceb0.png)

![image](https://user-images.githubusercontent.com/1212251/95500931-40bdb280-09b0-11eb-8e1e-99f8a3a06e76.png)

**Comment by isc-bsaviano** [comment]
This has been open for almost 4 years but hasn't drawn any interest.
