### ISSUE TITLE
Is vscode-objectscript truly a dependency?

### ISSUE THREAD

**Issue by osmattb** [intersystems/language-server#131]
In the documentation under dependency I noticed: 

> This extension requires that the vscode-objectscript extension be downloaded and enabled.

I was curious if this is true. I use vscode some, but majority of the time find my self in the terminal using vim. I found [coc.ncim](https://github.com/neoclide/coc.nvim) has language server support and considered looking into a plugin that could use this language server. 

Can this language-server integrate with other editors or does it strictly require vscode.

**Comment by isc-bsaviano** [comment]
@osmattb The vscode-objectscript is a strict dependency for now. The LS uses some custom messages to communicate with the client and relies on language definitions and virtual file systems that are provided by vscode-objectscript. While it is possible to write your own language client for another editor that has the same custom features implemented as vscode-objectscript, it would be a daunting task and would be contributed by the community.
