### ISSUE TITLE
Method keywords not supported

### ISSUE THREAD

**Issue by jtsalten** [intersystems/language-server#133]
This is a basic feature in class implementation that it seems just partially implemented as we don't get intellisense for options related to which keywords we have available:

Method xxxx() as %Status [... here I don't get any intellisense.

But, if I add:

Method xxxx() as %Status [ codemode = ... then I get the possible values

So, when we do Method xxxx() as %Status [ **<Ctrl-Shift>**....
we should get a list with:
Abstract
ClientName
CodeMode
Deprecated
ExternalProcName
Final
ForceGenerate
GenerateAfter
Internal
Language
NoContext
NotInheritable
PlaceAfter
Private
ProcedureBlock
PublicList
Requires
ReturnResultSets
ServerOnly
SoapAction
SoapBindingStyle
SoapBodyUse
SoapMessageName
SoapNamespace
SoapRequestMessage
SoapTypeNameSpace
SqlName
SqlProc
SqlRoutine
WebMethod
ZenMethod

and then further instellisense depending on the keyboard chosen.

**Comment by isc-bsaviano** [comment]
@jtsalten This is supported. Do you have any more context or an example you can post here that I can examine? Completion is triggered on a space for UDL compiler keywords so to get intellisense you need to type [_{space} then the suggestion list will appear.

**Comment by isc-bsaviano** [comment]
@jtsalten Any updates?

**Comment by jtsalten** [comment]
Now it works.... weird... :-( ... I think something is not working well behind the scenes with the extensions... it's not the first time that this happens to me. Something fails... then, withount any changes, after a restart or after "something"... it works.
