### ISSUE TITLE
Outdated documentation for $LISTFROMSTRING 

### ISSUE THREAD

**Issue by pjsulin** [intersystems/language-server#134]
$LISTFROMSTRING has wrong method defintion for it's signature causing false errors.

https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RCOS_FLISTFROMSTRING

The definition in the language server is missing the 3rd parameter, flag.

**Comment by isc-bsaviano** [comment]
@pjsulin What do you mean by "causing false errors"? Is it just that the documentation when you hover over $LISTFROMSTRING incorrect? Or do you mean something else? If it's an issue that you're seeing in the code and not just the hover documentation, can you please provide a code example and more context?

**Comment by pjsulin** [comment]
Seee images below show definition missing 3rd parameter, flag, the language server giving an error, the succussful output of the code and the definition from the docs. 



<img width="632" alt="Screen Shot 2021-02-20 at 7 22 28 AM" src="https://user-images.githubusercontent.com/4719356/108595208-a8b3da80-734c-11eb-9480-4db28861021f.png">

<img width="718" alt="Screen Shot 2021-02-20 at 7 22 17 AM" src="https://user-images.githubusercontent.com/4719356/108595215-af425200-734c-11eb-9cf4-be5df62ef978.png">

<img width="744" alt="Screen Shot 2021-02-20 at 7 26 11 AM" src="https://user-images.githubusercontent.com/4719356/108595273-f3355700-734c-11eb-971e-b269ad140c9c.png">

**Comment by isc-bsaviano** [comment]
@pjsulin Thanks for the update. There are two separate issues here, one with the documentation and another with the parser.  I will create a new issue for the parser bug and dedicate this one to the docs bug.
