### ISSUE TITLE
Better support for Peek Definition functionality

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#15]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/1212251/95502091-f76e6280-09b1-11eb-89c5-06e41a0cc362.gif)

**Comment by isc-bsaviano** [comment]
@daimor Do you still see this behavior in beta.5?

**Comment by daimor** [comment]
Yes, still the same

**Comment by isc-bsaviano** [comment]
Does User.Test exist? That shouldn't matter but I want to try to replicate the exact scenario

**Comment by daimor** [comment]
found one more place with the same issue
Yes, it's exists
![image](https://user-images.githubusercontent.com/1212251/96502649-c36d2a00-125a-11eb-9f1b-ede7f696b29d.png)

**Comment by isc-bsaviano** [comment]
I still can't reproduce this no matter where the class name is located. Are you just hovering? Do you have any non-default settings that might affect this? I tried on both existing and non existing classes and local and virtual files.

**Comment by daimor** [comment]
Hover with pressed command key.
And interestingly, that if the class extends only one class, it works well, but when it has more than one in parens, so, this happens.

**Comment by daimor** [comment]
it's not hover event, it's definition

**Comment by isc-bsaviano** [comment]
Ah, now I can see that behavior! I will investigate

**Comment by isc-bsaviano** [comment]
The issue is that I return a simple Location object for definition requests instead of a more detailed LocationLink.
