### ISSUE TITLE
Fix code completion for system functions/variables

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#16]
From @daimor in https://github.com/intersystems/language-server/issues/13#issue-717582501

![image](https://user-images.githubusercontent.com/1212251/95501065-6c409d00-09b0-11eb-8405-167b5991058d.png)

![image](https://user-images.githubusercontent.com/1212251/95501105-79f62280-09b0-11eb-8e4e-7b784fba548c.png)

**Comment by joelsolon** [comment]
Related to this (or perhaps a separate issue): the list that appears when you type the $ shows the functions in upper case. Does it make sense that the setting `"intersystems.language-server.formatting.system.case": "lower"` should cause the functions to appear in lower case?

**Comment by isc-bsaviano** [comment]
@joelsolon That's unrelated. Please file your suggestion as a separate issue.

**Comment by isc-bsaviano** [comment]
Closing as duplicate of #13
