### ISSUE TITLE
Improve the compilation error message for a missing } or ; in a class definition

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#166]
The compilation message for missing } or ; is:

`ERROR #5559: The class definition for class 'PackageName.ClassName' could not be parsed correctly, possibly due to non-matching {} or () characters. Edit the class and correct the problem.`

Suggested update:

`ERROR #5559: The class definition for class 'PackageName.ClassName' could not be parsed correctly, possibly due to non-matching {} or () characters, or a missing ; character.`

**Comment by isc-bsaviano** [comment]
@isc-solon This has nothing to do with the LS or VS Code. Compilation messages come directly from the server. You'll have to report this internally.
