### ISSUE TITLE
DocumentSymbolProvider: use more SymbolKind values

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#17]
For parameters use SymbolType.Constant

For indices use SymbolKind.Key

For XDATA and Storage use SymbolKind.Struct

This will align LS with what the ObjectScript did, and means the user can distinguish between these kinds of symbol when using the breadcrumb.

**Comment by isc-bsaviano** [comment]
Fixed in version 1.0.0-beta.5.
