### ISSUE TITLE
Automatically provide intellisense for certain % variables

### ISSUE THREAD

**Issue by Keshiyer** [intersystems/language-server#170]
Certain % variables always have certain types under certain contexts in Objectscript.
For example, in any subclass of %CSP.Page, %request has type %CSP.Request, %response has type %CSP.Response and %session has type %CSP.Session. It would be great if these variables were automatically had #dim applied to them rather than having to do that for every method that uses them.

Similarly, in [code generators](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GOBJ_generators#GOBJ_gen_methvalues) %code, %method, %compiledmethod, %class, %compiledclass should have the automatic #dim. 

Not sure if there are any other such % variables but these were the ones I could think of for now.

**Comment by isc-bsaviano** [comment]
Changed the title to make it clear the the request is for intellisense without having to `#Dim` these special variables, NOT for the LS to insert `#Dim` lines for these variables into the text of the file
