### ISSUE TITLE
Review checking of macro arguments

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#171]
I have some macros that take class names and method names as arguments, **unquoted**. The macro definition itself quotes the argument. For example:

`if $$$ClassExists(FCE.Currency)`

VS Code is checking the argument and reports `Local variable 'FCE' is undefined.`

I'm not sure if there's any solution. I'm reporting it for your consideration.

**Comment by isc-bsaviano** [comment]
@isc-solon There's nothing we can do here. There's no way for the parser to recognize that you're using `FCE.Currency` as an unquoted string.

**Comment by isc-solon** [comment]
Macro arguments can be **anything**: complete/valid or incomplete/invalid expressions, quoted or unquoted strings, other macros. I guess the pros of evaluating the arguments outweigh the cons of not evaluating the arguments, even though sometimes false negatives can be reported.
