### ISSUE TITLE
Intellisense for property keys

### ISSUE THREAD

**Issue by jtsalten** [intersystems/language-server#175]
Issue Type: <b>Bug</b>

Hi,
I've realized that Intellisense doesn't offer help for property keys during class definitions...

Property Emp as %Integer (MINVAL=0) [....  here it should offer help but it doesn't.

Regards

Extension version: 1.2.2
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.21GB free)|
|Process Argv|--crash-reporter-id 358469c0-fdbf-4ba7-9019-19e4937e55fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
bridge0708:30335490

```

</details>

**Comment by jtsalten** [comment]
![image](https://user-images.githubusercontent.com/6997495/125960902-85f904a9-3b71-49a0-b23f-b76bb5a0d7fc.png)

**Comment by isc-bsaviano** [comment]
@jtsalten You need to type a space after the open bracket. Space is one of our completion trigger characters.

**Comment by jtsalten** [comment]
Oh my... ok. But shouldn't it appear also, even without thw white space, if I click Ctrl-SpaceBar?

**Comment by isc-bsaviano** [comment]
It will if the space is already present. The completion provider is built around trigger characters so it will expect that trigger to already exist in the document. This is a known limitation of our provider (#13) that will require a lot of work to remedy and isn't a priority for us right now.

**Comment by jtsalten** [comment]
OK. Not intuitive... but now that I know of it I'll take care. Thanks.
