### ISSUE TITLE
Win32 error 126

### ISSUE THREAD

**Issue by isc-aray** [intersystems/language-server#176]
I have recently gotten a new laptop, and whenever I try to start the InterSystems Language Server, it fails with the below error:

```
Request initialize failed with message: Dynamic Linking Error: Win32 error 126
```

Here is the system information from VSCode:

CPUs | Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.75GB (18.84GB free)
Process Argv | --crash-reporter-id 66a8a6e9-47a0-4866-8430-963f33a9545c
Screen Reader | no
VM | 0%

**Comment by isc-bsaviano** [comment]
@isc-aray Are you using the latest versions of VS Code and all of our extensions?

**Comment by isc-aray** [comment]
@isc-bsaviano I am using Language Server 1.2.2, ObjectScript 1.0.13, and VSCode 1.58.2.

**Comment by isc-bsaviano** [comment]
@isc-aray I will have Andy look at this on Monday. I couldn't reproduce it on my Windows machine using the same versions.

**Comment by isc-AndrewCheshire** [comment]
@isc-aray Could you check the Language Server libraries folder on your machine please?

In vscode, select menu **View/Command Palette**, type **open ext** and select **Open Extensions Folder** from the drop-down list - _not_ "Open Extension Logs Folder".

This should open an Explorer window.  Navigate into these folders in turn:
- **intersystems.language-server-1.2.2**
- **server**
- **lib**
- **win**

If you don't now see a list of files with creation date and size select **View/Details** in Explorer.

Please check the dates and file sizes of what you see against the screenshot below:

![image](https://user-images.githubusercontent.com/12095368/126190165-f33bfcd8-30e1-4721-9e2a-38469c815137.png)

If they don't match please take a screenshot of your folder using Alt+PrtScr and post that.

If they match it means that some dependency of these libraries is missing.  I'll post how to get a log of low-level events for the process, which should tell us what's missing.

**Comment by isc-aray** [comment]
After rebooting the machine, I am no longer experiencing this issue.
