### ISSUE TITLE
Else command incorrectly shortened to "e" during formatting

### ISSUE THREAD

**Issue by ChrisJMarais** [intersystems/language-server#181]
The problem is with if statements that have an else

Config
=====
"intersystems.language-server.formatting.commands.case": "lower",
"intersystems.language-server.formatting.commands.length": "short",

Code
====
i (a=b) {                                   //<------------- if is shortened to i (this works)
} elseif (c=d) {                          //<------------- elseif is not shortened (this is according to documentation)
} e {                                          //<------------- else is shortened to e (this gives an error and is not according to documentation)
}

IS Documentation on IF statements
========================
Synopsis
IF expression1,... {
}
ELSEIF expression2,... {
}
ELSE {
}

or

I expression1,... {
}
ELSEIF expression2,... {
}
ELSE {
}

**Comment by isc-bsaviano** [comment]
@ChrisJMarais Thanks for the detailed issue report
