### ISSUE TITLE
Language Server crashes on InterSystems macs due to unsigned libraries

### ISSUE THREAD

**Issue by MakarovS96** [intersystems/language-server#182]
![image](https://user-images.githubusercontent.com/19629483/128817737-f0b795c6-a3b3-4ab6-8f51-62910d176a00.png)

**Comment by MakarovS96** [comment]
platform: macOS 11.4 x86
vscode version: 1.59.0
ext version: 1.2.2

**Comment by isc-bsaviano** [comment]
@MakarovS96 Are you using an InterSystems machine?

**Comment by MakarovS96** [comment]
@isc-bsaviano Yes

**Comment by isc-jsmith** [comment]
I've hit the same issue. Also using an InterSystems machine.

**Comment by isc-bsaviano** [comment]
I am working on a solution to this issue. The next language server version will contain a fix.  I don't have an ETA yet

**Comment by amirsamary** [comment]
Having the same issue here. Thank you! Amazing product! Love it!

**Comment by isc-bsaviano** [comment]
@MakarovS96 @isc-jsmith @amirsamary The directions to resolve this issue are in my most recent post in the Technical Services Information team. Please follow up with me there if you're still experiencing issues.

**Comment by j4y33** [comment]
I have the same issue with newest version of VSCode

**Comment by isc-bsaviano** [comment]
@j4y33 If you're an InterSystems employee, message me internally. If not, you're experiencing a different bug so please open a new issue with more details.
