### ISSUE TITLE
Request initialize failed with message: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by pvdmm** [intersystems/language-server#186]
Issue Type: <b>Bug</b>

When i try to start the InterSystems Language Server, it fails with the below error:

Request initialize failed with message: Dynamic Linking Error: Win32 error 126

I have tried another servers and reinstall the extension, but i always got the same error.

Extension version: 1.2.2
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (2.08GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 72539a58-9d25-42fb-993f-64f561be6427|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30350172
bridge0723:30353136
vsdyn478:30354110

```

</details>

My server lib folder:

![image](https://user-images.githubusercontent.com/42217732/130085743-4d0c8d4d-6236-4be8-b3d3-3c02c6854b0d.png)

**Comment by isc-bsaviano** [comment]
@pvdmm Have you experienced this issue with previous versions of the extension? Your libraries look fine to me. This might be similar to #176

**Comment by pvdmm** [comment]
> rienced this issue with previous versions

It's a new windows instalattion, i have only tried this version and never worked with me. I saw the #176 issue and checked the files, also rebooted the machine after reinstalling the extesion, but still not working.

**Comment by isc-bsaviano** [comment]
Thanks for the extra info. Can you try installing a previous version to see if that works? You can do that by clicking on the extensions logo in the side bar, clicking on the gear icon next to the language server extension, and then selecting 'Install another version...'. Try to install version 1.2.1 and let me know how it goes.

**Comment by pvdmm** [comment]
Same error on  these versions 1.2.1, 1.2.0, 1.1.6.

I also removed my corp antivirus.

Uncaught Errors (1)
Request initialize failed with message: Dynamic Linking Error: Win32 error 126

Developer console:

![image](https://user-images.githubusercontent.com/42217732/130093183-25bcac62-12f5-493d-a36a-96cd0b11e4b1.png)

**Comment by isc-bsaviano** [comment]
Thanks for checking that. Is there anything unique about your windows install? I have a desktop running windows 10 pro 10.0.19043 (same as yours) and have never experienced issues with the language server.

**Comment by pvdmm** [comment]
> Thanks for checking that. Is there anything unique about your windows install? I have a desktop running windows 10 pro 10.0.19043 (same as yours) and have never experienced issues with the language server.

Nothing special, just the windows update that is controlled by the company.
I have tried to uninstall the antivirus because another employees with Windows have the same issue, but it didn't solve the problem.

I'm also using **proposed-api**, is there any connection?

**Comment by isc-bsaviano** [comment]
Enabling proposed APIs should have no effect on the language server. I'm going to assign this issue to the developer who works on the parser libraries. He will be back online on Monday.

**Comment by pvdmm** [comment]
> Enabling proposed APIs should have no effect on the language server. I'm going to assign this issue to the developer who works on the parser libraries. He will be back online on Monday.

Ok, thanks @isc-bsaviano , i also tried it on my personal laptop, that doesn't have windows polices and blocks, same issue.

**Comment by isc-bsaviano** [comment]
How recently did you update those windows machines? I updated mine a few days ago but maybe I'm missing a more recent OS update that causes this issue.

**Comment by gjsjohnmurray** [comment]
@pvdmm have these Windows machines previously had InterSystems Studio installed? I'm wondering if the extension relies on the presence of something (e.g. an MSVC runtime DLL) that isn't bundled with it.

**Comment by pvdmm** [comment]
This one was updated last week (21H1 - build 19043.1165) . The other has the same version (21H1) with last update in July and when I was testing, windows downloaded a new update, so I ran the tests before and after the update.

> How recently did you update those windows machines? I updated mine a few days ago but maybe I'm missing a more recent OS update that causes this issue.

This one was updated last week (21H1 - build 19043.1165) . The other has the same version (21H1) with last update in July and when I was testing, windows downloaded a new update, so I ran the tests before and after the update.

**Comment by pvdmm** [comment]
> @pvdmm have these Windows machines previously had InterSystems Studio installed? I'm wondering if the extension relies on the presence of something (e.g. an MSVC runtime DLL) that isn't bundled with it.

Nothing in mine, but in a coworker that doesn't work either, only has Studio installed (InterSystems Studio Cliente 2020.2.0 Build 211) without Iris/Caché

**Comment by pvdmm** [comment]
> @pvdmm have these Windows machines previously had InterSystems Studio installed? I'm wondering if the extension relies on the presence of something (e.g. an MSVC runtime DLL) that isn't bundled with it.

I installed the latest version of Iris, restarted and still not working.

![image](https://user-images.githubusercontent.com/42217732/130241647-d38e28ee-f05c-4492-a104-c0f22e683d39.png)

**Comment by isc-AndrewCheshire** [comment]
@pvdmm Would it be possible for you to install a Microsoft logging tool to monitor VSCode while it's starting up?  I need this information to find out which DLL dependency is not loading.

If you are in a position to do this I'll send you full instructions.

**Comment by pvdmm** [comment]
> @pvdmm Would it be possible for you to install a Microsoft logging tool to monitor VSCode while it's starting up? I need this information to find out which DLL dependency is not loading.
> 
> If you are in a position to do this I'll send you full instructions.

Sure, please send the instructions

**Comment by isc-AndrewCheshire** [comment]
@pvdmm The tool is _Process Monitor v3.84_, available from https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

The downloaded file is a .zip so you need to extract the contents into some folder - it doesn't have an installer, as such, so I think that it can be removed just by deleting the folder.

First of all, make sure that VSCode is running.

Run Procmon64.exe and press control+L to pop up the Filters dialog.

- click the first column (under "Display entries matching these conditions") and scroll down to "Description"
- click the second column and scroll to "contains"
- click the third column and scroll to "Visual Studio Code"

Now click the "Add" button and the new condition should be added to the main part of the dialog.
Click "OK"

Next, exit from VSCode.

Back in procmon enable event logging using control+E.

Run VSCode again, wait for it to start up and show the error message and then switch to procmon and disable event logging using control+E again.

In procmon press control+S to save the log.  Select "Events displayed using current filter" and "Comma separated values".  Choose a file location for the saved file and click OK.

Don't upload the raw log, compress it to a zip file first - compression is about 20x in this format.  Then upload the zip with a Github comment.

Thanks!

**Comment by pvdmm** [comment]
[Logfile-VsCode.zip](https://github.com/intersystems/language-server/files/7034285/Logfile-VsCode.zip)


> @pvdmm The tool is _Process Monitor v3.84_, available from https://docs.microsoft.com/en-us/sysinternals/downloads/procmon
> 
> The downloaded file is a .zip so you need to extract the contents into some folder - it doesn't have an installer, as such, so I think that it can be removed just by deleting the folder.
> 
> First of all, make sure that VSCode is running.
> 
> Run Procmon64.exe and press control+L to pop up the Filters dialog.
> 
> * click the first column (under "Display entries matching these conditions") and scroll down to "Description"
> * click the second column and scroll to "contains"
> * click the third column and scroll to "Visual Studio Code"
> 
> Now click the "Add" button and the new condition should be added to the main part of the dialog.
> Click "OK"
> 
> Next, exit from VSCode.
> 
> Back in procmon enable event logging using control+E.
> 
> Run VSCode again, wait for it to start up and show the error message and then switch to procmon and disable event logging using control+E again.
> 
> In procmon press control+S to save the log. Select "Events displayed using current filter" and "Comma separated values". Choose a file location for the saved file and click OK.
> 
> Don't upload the raw log, compress it to a zip file first - compression is about 20x in this format. Then upload the zip with a Github comment.
> 
> Thanks!

@isc-AndrewCheshire log attached

**Comment by isc-AndrewCheshire** [comment]
@pvdmm Thanks for the log, I think that your problem is due to a couple of missing DLLs: msvcp120.dll and msvcr120.dll

These can be installed using the Visual C++ 2013 redistributable package available from https://support.microsoft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a5-4e26-c290-517b-8da6cfdf4f10

This is a link to an page talking about a bugfix update but it is the latest version (5) of these tools, linked from a Microsoft page titled "The latest supported Visual C++ downloads".

Please install this and then try running VSCode again.


If this fixes your problem the Language Server team can work out the best way to fix this issue for future installations of the extension.

**Comment by pvdmm** [comment]
> @pvdmm Thanks for the log, I think that your problem is due to a couple of missing DLLs: msvcp120.dll and msvcr120.dll
> 
> These can be installed using the Visual C++ 2013 redistributable package available from https://support.microsoft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a5-4e26-c290-517b-8da6cfdf4f10
> 
> This is a link to an page talking about a bugfix update but it is the latest version (5) of these tools, linked from a Microsoft page titled "The latest supported Visual C++ downloads".
> 
> Please install this and then try running VSCode again.
> 
> If this fixes your problem the Language Server team can work out the best way to fix this issue for future installations of the extension.

Thanks man, it's worked now! 💯 👍
