### ISSUE TITLE
Error while hovering over non-existent class

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#191]
Issue Type: <b>Bug</b>

Opening a UDL class (not on the server) from the source tree and moving the mouse over the extends causes a hover error due to the non existent class in the list

[Trace - 10:26:45 AM] Received response 'textDocument/hover - (5231)' in 5ms. Request failed: Request textDocument/hover failed with message: Cannot read property 'content' of undefined (-32603).
[Error - 10:26:45 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'content' of undefined
  Code: -32603 
[Trace - 10:27:00 AM] Sending request 'textDocument/hover - (5232)'.
Params: {
    "textDocument": {
        "uri": "file:///private/tmp/jb%28p4v%29/USMBP16jbourett_perforce_1666/healthshare/hscore/latest/databases/hslib/cls/HS/Gateway/HL7/InboundProcess%231.cls"
    },
    "position": {
        "line": 7,
        "character": 0
    }
}

Extension version: 1.2.3
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.83GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 87c1cdb2-fea9-4db7-a129-27164053787c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30322571
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
javagetstartedt:30351793
vsdyn420:30356812
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by bourette** [comment]
Okay, I just figured it out.  I clicked on the latest history item for //healthshare/hscore/latest/databases/hslib/cls/HS/Gateway/HL7/InboundProcess.cls which opened as  /private/tmp/jb(p4v)/USMBP16jbourett_perforce_1666/healthshare/hscore/latest/databases/hslib/cls/HS/Gateway/HL7/InboundProcess#1.cls

**Comment by isc-bsaviano** [comment]
Opened that exact class, still not seeing an error.
