### ISSUE TITLE
Language Server fails on a 32-bit Windows 7 workstation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#197]
![image](https://user-images.githubusercontent.com/6726799/137769307-3cab63db-13cf-4f6a-b5ce-f82aca4d5ffc.png)

I'm not certain if this is cause by the platform being 32-bit, or Windows 7, or by something else.

Is 32-bit Windows a supported platform for LS?

**Comment by isc-AndrewCheshire** [comment]
@gjsjohnmurray No, 32-bit Windows isn't supported.
