### ISSUE TITLE
Extra slash added before `pathPrefix` causes 404 errors

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/language-server#199]
Attempting to code a business operation in a fresh HSUCR 2021.1 Foundation namespace and constantly getting hit with this error, no matter what class I open. Even hovering over something common/simple like Ens.Request produces this error.

I have found other closed bugs from last year that had similar errors but all dealing with other scenarios.

**Comment by isc-bsaviano** [comment]
@CraigRegester Just to clarify, are you only seeing this bug when you hover over a class name like `Ens.Request`, or are you also seeing it when you hover over other elements like class members? Also, you're using the latest versions of all 3 extensions, correct?

**Comment by CraigRegester** [comment]
@isc-bsaviano Everywhere, I used the Ens.Request example just to show that even with a base level object that I know "works" (with the language server) in our I4H isfs instances, I was still getting the error. 

UCR is relatively new to us as an org, and I just started using vs code with it so at first I thought the errors were something I configured improperly for vscode, but validated all that. Will check again. 

Yes, latest version of all. Also closed all VSCode windows and relaunched workspace to no avail.

**Comment by isc-bsaviano** [comment]
@CraigRegester I just installed a new HealthShare with $ZV `IRIS for UNIX (Apple Mac OS X for x86-64) 2020.1 (Build 217_1_20728U) Fri Apr 16 2021 11:15:46 EDT`, created a new Foundation namespace and opened class `HS.Director`. I'm not seeing any errors when hovering. Does this resemble your setup?

**Comment by CraigRegester** [comment]
@isc-bsaviano Yes - relatively close to our setup, just different base OS.
IRIS for UNIX (IBM AIX for System Power System-64) 2020.1 (Build 217_1_20728U) Fri Apr 16 2021 11:20:49 EDT

I just opened up HS.Director.cls, clicked into the window (giving it focus) - using **ClassMethod StartAll** as my point of reference, if I hover over %Status, I get:

```
[Error - 2:19:12 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'content' of undefined
  Code: -32603 

```
If I hover over ..invokeAll, I get a slightly different error:

```
[Error - 2:20:14 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot use 'in' operator to search for 'content' in undefined
  Code: -32603 
```

I tried the same thing in my I4H 2021.1 instance (HS.Director) and not seeing that error. So, clearly, something else is interfering/different. Thinking... 

The primary difference I see is that I4H uses a separate web gateway that doesn't make use of CSP Config Name prefixes. Our UCR environment shares a web gateway with ODS so we use a /ucr or /ods prefix like;

```
        "ucr-int1-devucr": {
            "webServer": {
                "scheme": "https",
                "host": "hs-dev.ourdomain.com",
                "port": 443,
                "pathPrefix": "/ucr"
            },
            "description": "HealthShare UCR DEV",
			"username": "myUserIdIsHere"
        },
```
Any chance that has a play in the issue?

**Comment by isc-bsaviano** [comment]
@CraigRegester Thanks for the detailed response. The error message is different but I believe the cause is the same. The REST call to the server is failing, which is why you're running into issues where a variable is `undefined` when you'd expect it to have a value. Can you go into your settings and set the value of `intersystems.language-server.trace.server` to `"messages"`? That will create the `InterSystems Language Server` Output channel, which will log, among other things, the error that's occurring when the LS tries to make REST request to that server.

**Comment by CraigRegester** [comment]
@isc-bsaviano 

```
[Trace - 2:58:07 PM] Sending request 'textDocument/hover - (6)'.
[Trace - 2:58:07 PM] Received response 'textDocument/hover - (6)' in 124ms. Request failed: Request textDocument/hover failed with message: Cannot read property 'content' of undefined (-32603).
[Error - 2:58:07 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'content' of undefined
  Code: -32603 
[Trace - 2:58:27 PM] Sending request 'textDocument/hover - (7)'.
[Trace - 2:58:27 PM] Received response 'textDocument/hover - (7)' in 118ms. Request failed: Request textDocument/hover failed with message: Cannot use 'in' operator to search for 'content' in undefined (-32603).
[Error - 2:58:27 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot use 'in' operator to search for 'content' in undefined
  Code: -32603 
```

**Comment by isc-bsaviano** [comment]
Sorry, I read through you message quickly and didn't realized that you already had the trace on. I was hoping that we'd see an error related to the REST request failing. Do you have Wireshark or another HTTP trace service on your machine? I would like to see the the HTTP request and response objects for the REST request when you hover over `%Status` or `..invokeAll()`.

**Comment by CraigRegester** [comment]
Unfortunately it seems I cannot use Wireshark to see the requests unencrypted. With verbose mode turned on in settings in VS Code for the language server, I can see this hovering over %Status:

```
[Trace - 4:08:23 PM] Sending request 'textDocument/hover - (17)'.
Params: {
    "textDocument": {
        "uri": "isfs://ucr-int1-devucr:egfaepic/HS/Director.cls"
    },
    "position": {
        "line": 14,
        "character": 88
    }
}


[Trace - 4:08:23 PM] Received response 'textDocument/hover - (17)' in 86ms. Request failed: Request textDocument/hover failed with message: Cannot read property 'content' of undefined (-32603).
[Error - 4:08:23 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'content' of undefined
  Code: -32603 
```

I tinkered with the i4h instance so I could see what the payload should look like and saw this:

{"query":"SELECT Description FROM %Dictionary.CompiledClass WHERE Name = ?","parameters":["%Library.Status"]}

Then using postman, I was able to setup a request to emulate what VS Code is supposed to be doing (I believe, anyway), and it works just fine...

![image](https://user-images.githubusercontent.com/65192819/140415020-41345fd7-6f73-4437-b519-095eb96fe7cb.png)

Not sure if this helps at all but I'm at a bit of a loss.

**Comment by isc-bsaviano** [comment]
@CraigRegester That definitely helps! That query payload is exactly what I'd expect. Maybe the issue is with how I apply the path prefix. If you turn on your instance's HTTP trace on via the `Web Gateway Management` page, do you see that request showing up when you hover in VS Code?

**Comment by CraigRegester** [comment]
Glad it helps  :) Well.. I was going to say 'I swear I tried that (turning on the trace in WG)' and got nothing but I just tried again after clearing up a log permission issue and now I see the traces. 🤦🏼‍♂️ 

![image](https://user-images.githubusercontent.com/65192819/140416983-485429d3-1f59-4406-a595-c24c9c12f8d5.png)

The 404 wasn't what I expected to see. Double-slash in front of the prefix?

**Comment by isc-bsaviano** [comment]
@CraigRegester Yup, looks like the LS is adding an extra slash before the `pathPrefix`:

https://github.com/intersystems/language-server/blob/292df30159f09c40f677ac832b3acb4b29f3308f/server/src/server.ts#L2346-L2351

I'll get this fixed tomorrow.

**Comment by CraigRegester** [comment]
Thx @isc-bsaviano - I believe I put the prefix in the settings file based on the documentation page, but I guess probably best to handle any manner of sin a user like me puts in there, hah.

Thanks for your persistence guiding me along', much appreciated.

**Comment by isc-bsaviano** [comment]
@CraigRegester Thanks for helping me debug this. Your `pathPrefix` is perfectly valid. In fact, the server manager extension requires that you include the leading slash:

```json
"pathPrefix": {
   "type": "string",
  "description": "Optional prefix for the path to the resource, for example '/dev' or '/vm/test'. Only needed when one web server publishes services on behalf of multiple InterSystems servers.",
  "pattern": "^(/[^/]+)*$"
}
```

**Comment by isc-bsaviano** [comment]
@CraigRegester Please download the beta vsix found [here](https://github.com/intersystems/language-server/releases/tag/v1.2.6-dev.199) and let me know if if it works for you

**Comment by CraigRegester** [comment]
Success! Thanks for hitting this so quickly.

```
[Trace - 9:06:48 AM] Received response 'textDocument/hover - (8)' in 217ms.
Result: {
    "contents": [
        "%Library.Status",
        "The **%Status** data type class is used to represent an error status code.\n\nMany of the methods provided by the _class Library_ return error status information using the **%Status** data type. The include file, _%occStatus.INC_, contains several macro definitions that are useful in testing the value of an error code in **%Status** format.\n\nThese macros include:\n\n*   `$$$ISOK(status:%Status)` returns true (1) if the status code status does not represent an error condition.\n*   `$$$ISERR(status:%Status)` returns true (1) if the status code status represents an error condition.\n\nYou can get a more detailed description of an error by using the system-provided $system.Status.DecomposeStatus(status:%Status,&err,flag) routine.\n\nThis routine takes a status code and returns an array of error strings.\n\nFor example:  \n\nSet status=obj.%Save() If $$$ISERR(status) Do $system.Status.DecomposeStatus(status,.err,\"-d\") For i=1:1:err Write err(i),!"
    ],
    "range": {
        "start": {
            "line": 7,
            "character": 73
        },
        "end": {
            "line": 7,
            "character": 80
        }
    }
}
```

**Comment by isc-bsaviano** [comment]
Awesome! Glad to hear it. I will release a new version shortly.
