### ISSUE TITLE
Class parser interprets modulo operator as a CSP extension

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#204]
Class %Library.PopulateUtils
`density#($$$PRand(density)+1)` marked as error, and everything below
![image](https://user-images.githubusercontent.com/1212251/142842771-6d563cbb-a336-42e5-93e1-2d71332d04fe.png)

**Comment by isc-bsaviano** [comment]
@isc-AndrewCheshire I inspected the tokens and the bug is that `#(` is parsed as a CSP extension, when it should be a modulo operator and delimiter.
