### ISSUE TITLE
Support InterSystems Server Manager 3.0's `AuthenticationProvider`

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#207]
See https://github.com/intersystems-community/intersystems-servermanager/pull/109

**Comment by gjsjohnmurray** [comment]
Pre-release v1.3.2021121001 of vscode-objectscript is now available on Marketplace. It uses Server Manager 3's authentication provider and no longer returns password in its `serverForUri` API response. Please verify that your next LS VSIX will work correctly alongside this.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I just installed the pre-release versions of the main and server manager extensions and a beta version of the LS with the auth provider code in my VS Code Insiders. When I opened a workspace with isfs files open, I got an authentication provider promt for the main extension, but not the LS. I checked my LS logs and it appears that the main extension is still sending a password in `serverForUri()`

**Comment by gjsjohnmurray** [comment]
Sorry about that. I have just published a new pre-release (1.3.2021121601) which I hope works properly.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano when I told VS Code to check for extension updates it reported the new one as available (I was already using the earlier pre-release). After clicking the Update button it became a Reload button. I did so, but after the reload it had switched to the release version, so I had to opt in to pre-release again. I'll be interested to hear if you see the same happen.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Just updated to the newer pre-release. I didn't see your behavior when I installed, it correctly had the new pre-release installed after the reload. This is on the latest Insiders though, not stable. With the new pre-release, I see the expected prompt for the auth provider and once I grant permission the LS appears to work fine.
