### ISSUE TITLE
ILS requests all fail with resolveFromUri failed unexpectedly

### ISSUE THREAD

**Issue by isc-aray** [intersystems/language-server#212]
Since yesterday's update, I am now getting an error whenever I try to use any language-server features:

![image](https://user-images.githubusercontent.com/43610734/149522050-46ce8fbe-3525-436f-9069-464ed51f2743.png)

The error recorded in the output log is:
```
[Error - 8:22:07 AM] Request textDocument/hover failed.
  Message: Request intersystems/server/resolveFromUri failed unexpectedly without providing any details.
  Code: -32603 
```

It appears that the server is responding appropriately to a request to the `atelier/v4/*/doc/*` API, either with `200 OK` or `304 Not Modified` (if the `if_none_match` header is specified), but VSCode is failing to handle the response correctly.

A request to `http://[server name omitted]:52773/api/atelier/v4/%25SYS/doc/%25SYSTEM.Status.cls` returns:

```
{
    "status": {
        "errors": [],
        "summary": ""
    },
    "console": [],
    "result": {
        "name": "%SYSTEM.Status.cls",
        "db": "IRISLIB",
        "ts": "2021-11-09 19:15:10.299",
        "upd": true,
        "cat": "CLS",
        "status": "",
        "enc": false,
        "flags": 0,
        "content": [
            ...
        ]
    }
}
```

**Comment by isc-bsaviano** [comment]
@isc-aray Are you working client side or server side? If the latter, can you send me your `.code-workspace` file (with any sensitive info redacted)? I have a server-side isfs workspace using LS 1.2.8, main extension 1.2.2 and server manager 2.0.6 and everything is working fine

**Comment by isc-aray** [comment]
I am working client-side, I think. I have all the files locally on my machine and hook up various instances to it as required to do my work.

**Comment by isc-bsaviano** [comment]
Ok, I just checked using a class on my local file system and I still couldn't see your error. Can you confirm that you're using the same extension versions as me? Those are the latest stable released versions.

**Comment by isc-aray** [comment]
ILS 1.2.8
ObjectScript 1.3.2022011401
VSCode 1.63.2
I do not use Server Manager because I have a large number of short-lived instances that pop into existence and then get deleted a few days later

**Comment by isc-bsaviano** [comment]
I have no idea what version of the main extension that is. The version number looks like a pre-release (all of our pre-releases have the date format) so it shouldn't be in the main release channel. I suggest manually rolling back to 1.2.2 (or downloading a 1.2.3 beta release from [here](https://github.com/intersystems-community/vscode-objectscript/releases)) until I can figure out what's in that version and properly test the LS against it. Sorry for the confusion.

**Comment by isc-bsaviano** [comment]
That's good to hear. I will leave this issue open so other people experiencing this issue can see it.

**Comment by isc-bsaviano** [comment]
@isc-aray Main extension version 1.4.0 is out. Do you still see this issue with that version?

**Comment by isc-bsaviano** [comment]
@isc-aray Version 1.4.0 is bad. A version 1.4.1 should be out soon. Sorry for the mix up

**Comment by isc-bsaviano** [comment]
Version 1.4.1 is out

**Comment by isc-aray** [comment]
Can confirm issue does not occur in 1.4.1. Thank you again!
