### ISSUE TITLE
`vh` and `vw` CSS units are marked as invalid

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#213]
![image](https://user-images.githubusercontent.com/6726799/150129911-042baf0e-6277-4271-9dee-7036f71633d7.png)

Source is from https://github.com/intersystems/TestCoverage/blob/master/cls/TestCoverage/UI/Application.cls

Documentation: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#lengths

**Comment by isc-bsaviano** [comment]
Reported internally as DP-411241
