### ISSUE TITLE
Suppress or prioritize generated methods from intellisense pick-lists

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#215]
The auto-complete pick-lists put generated methods at the top. Since the use of these methods is less common I would like a way to either suppress them completely from the auto-complete or at least prioritize the list to make the actual member the first pick.

Example 1:  Here `LastName` or `LastEnteredBy` should be first (simple string property), not the generated methods

<img width="567" alt="lang-getset" src="https://user-images.githubusercontent.com/669176/153246313-b8a47230-dfaf-4819-8615-cd203461924e.png">

Example 2: Here `Addresses` should be first (list of serial objects)

<img width="318" alt="lang-objlist" src="https://user-images.githubusercontent.com/669176/153246343-23c8400e-29bb-45c9-929c-1c6e9df14ff5.png">

**Comment by isc-bsaviano** [comment]
@mvhenderson I will check my sorting. I know that I have code that is supposed to show class members that originate in the base class first (with inherited stuff after) but that may not take into account these generated methods.

**Comment by isc-bsaviano** [comment]
@mvhenderson Figured it out. The queries that I use to find all valid class members used the wrong value for the Origin column, which is used for sorting. This was only a problem for inherited properties.
