### ISSUE TITLE
Noisy failure when `"active": false` in `objectscript.conn`

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#216]
Issue Type: <b>Bug</b>

This looks similar to #211

Using the client-side development paradigm, if a connection is configured but disabled (e.g. by togging it from its panel in the status bar), the LS output channel reports a lot of failure messages when a class is opened. And on my 1.65 Insiders I also get notifications about it crashing repeatedly.

Extension version: 1.2.8
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I see some axios errors in the Output channel but even on Insiders I'm not seeing any crashes.

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/153672017-57a2c8bd-6267-48f1-85bc-1245da0c9af2.png)

```
Version: 1.65.0-insider (user setup)
Commit: bb221a61d29deabd99ee9431736d04f2175cb596
Date: 2022-02-11T05:19:13.554Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Windows_NT x64 10.0.22000
```
Only enabled extensions for this workspace are the ObjectScript Extension Pack ones.

![image](https://user-images.githubusercontent.com/6726799/153672397-fa2e0ee5-5638-441b-a309-2f2ea69d2fa6.png)

From the LS output channel:
```
    method: 'post',
    url: 'http://127.0.0.1:57901/api/atelier/vundefined/USER/action/query',
```

The Atelier version being used looks suspect.

**Comment by gjsjohnmurray** [comment]
.vscode\settings.json

```json
{
    "objectscript.conn": {
        "server": "iris201",
        "ns": "USER",
        "active": false
    }
}
```

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I sent you a beta vsix to test via FTP
