### ISSUE TITLE
Improve semantic tokens for macro values

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#22]
![image](https://user-images.githubusercontent.com/1212251/95751973-02720d00-0ca8-11eb-8cdb-2a73e894e710.png)

I do not if it how it supposed to be, but it looks quite strange

**Comment by isc-bsaviano** [comment]
The tokens are "correct" in the sense that they're the same as Studio but I agree that this looks weird because the two tokens are assigned different colors (in Studio those token types are given the same color by default).

**Comment by whitten** [comment]
> The tokens are "correct" in the sense that they're the same as Studio but I agree that this looks weird because the two tokens are assigned different colors (in Studio those token types are given the same color by default).

Is $$$ a single token or is $$$OK two tokens ($$$ and OK ) ?

**Comment by isc-bsaviano** [comment]
@whitten Generally macros are 2 tokens, $$$ and then the name of the macro. I don't know for sure if that's uniform though.

**Comment by isc-bsaviano** [comment]
Since a macro value can be any string of text, the work required to tokenize them differently far exceeds the value of doing that work.
