### ISSUE TITLE
Extension reports noisy error message when REST request fails

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#220]
Seeing this after upgrading the extension

```
(node:23112) UnhandledPromiseRejectionWarning: Error: Request intersystems/server/makeRESTRequest failed with message: **Cannot read property 'data' of undefined**
    at c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708402
    at c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:708696
    at Immediate.<anonymous> (c:\Users\142990\.vscode\extensions\intersystems.language-server-2.0.0\server\out\server.js:2:709061)
    at processImmediate (internal/timers.js:461:21)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:23112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 1:27:57 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:02 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:04 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 1:28:49 PM] Request textDocument/hover failed.
  Message: Request intersystems/server/makeRESTRequest failed with message: Cannot read property 'data' of undefined
  Code: -32603 
```

Reported by @CraigRegester [here](https://github.com/intersystems/language-server/issues/219#issuecomment-1083425376)

**Comment by isc-bsaviano** [comment]
@CraigRegester

Try this VSIX and let me know if it works. The issue is that the new code for making REST requests wasn't handling null/undefined responses correctly.

[language-server-win32-x64-2.0.1-beta.1.vsix.zip](https://github.com/intersystems/language-server/files/8383042/language-server-win32-x64-2.0.1-beta.1.vsix.zip)

**Comment by CraigRegester** [comment]
![image](https://user-images.githubusercontent.com/65192819/160902729-173f2636-89ab-4e52-b572-b4a745a57a99.png)
That seemed to do the trick - getting help text now at least and no others in the Output window.

Fyi, 2.0.0 broke trusted CA certs as well, not just local ones. Guessing you knew that but just sharing.

**Comment by isc-bsaviano** [comment]
Just to confirm, you mean 2.0.0 did not resolve #219?

**Comment by CraigRegester** [comment]
Saying 2.0.0 made #219 worse initially. Whereas before with my UCR instance (which uses a Trusted CA Cert - not a local CA Cert) I could use the language server just fine, once 2.0.0 was installed, UCR was getting the exact same errors I shared today on #219 .

 Sorry for the confusion. Two different domains and instances, one uses a Trusted CA Cert, other uses a Local CA Cert. Former worked pre-2.0.0, latter did not. Both didn't work with 2.0.0.
 
 With 2.0.1, they're both working at the moment!

**Comment by isc-bsaviano** [comment]
Ok, I'm glad that everything is working now. If you over over a class, you see documentation when you're connected to either one of those instances, right? Hover for classes always makes a REST request so that's an easy way to test that they're going through

**Comment by CraigRegester** [comment]
If I hover over a function like $PIECE or $LISTNEXT, it definitely works on both.

If I hover over a class, I'm not sure that is working on either.... but it's not throwing any errors.

**Comment by isc-bsaviano** [comment]
Ok, there may still be a problem then. Does go to definition on a class work?

**Comment by CraigRegester** [comment]
No sir, it doesn't, on either.

[Trace - 2:26:12 PM] Received response 'textDocument/definition - (61)' in 6ms.
No result returned.

**Comment by CraigRegester** [comment]
No prob - here's some verbose logging that generated when I opened up EnsLib.HL7.Message

[trace.txt](https://github.com/intersystems/language-server/files/8383198/trace.txt)

**Comment by isc-bsaviano** [comment]
@CraigRegester Figured it out, it has to do with the npm module that I use to pass cookies when I do the requests. I'll have a fix for you soon.
