### ISSUE TITLE
Add embedded language Request Forwarding for HTML, CSS, JavaScript, etc.

### ISSUE THREAD

**Issue by Christian-Martinez1** [intersystems/language-server#228]
Hello,

I would like to request that Request Forwarding be added to the client extension for the Intersystems Language Server. While the language server does have markup for HTML elements, JS variables and functions, etc, there is no hover box suggestions or auto-completion (aside from the auto-close tag as that is a different extension) as seen below:

https://user-images.githubusercontent.com/43798323/168807166-c292c6bf-d815-4187-9594-639c2b214d47.mp4

However once the language is switched to HTML, embedded style hover boxes and MDN reference for html elements/tags as well as auto-completion is enabled again as seen below:

https://user-images.githubusercontent.com/43798323/168808232-3190ebd7-f08f-4097-a407-e9a485a9c435.mp4

Can you all add Request Forwarding for languages other than Cache/ObjectScript so that we may get default VS Code functionality for them? Here is a link to the VS Code documentation on how to request forward and it links a github sample project as well that implements request forwarding for a 'new' sample language called html1: https://code.visualstudio.com/api/language-extensions/embedded-languages

**Comment by isc-bsaviano** [comment]
@Christian-Martinez1 The Language Server is not registered to provide Intellisense for HTML files so it shouldn't be conflicting with the default HTML support for them:

https://github.com/intersystems/language-server/blob/1fddccd038f3d87531d6f58ae2656f95ba83d07b/client/src/extension.ts#L77-L84

If you want HTML Intellisense in embedded HTML within ObjectScript or CSP then request forwarding would potentially solve that problem.

**Comment by Christian-Martinez1** [comment]
> @Christian-Martinez1 The Language Server is not registered to provide Intellisense for HTML files so it shouldn't be conflicting with the default HTML support for them:
> 
> https://github.com/intersystems/language-server/blob/1fddccd038f3d87531d6f58ae2656f95ba83d07b/client/src/extension.ts#L77-L84
> 
> If you want HTML Intellisense in embedded HTML within ObjectScript or CSP then request forwarding would potentially solve that problem.

Correct, that is what I am requesting; for embedded HTML, CSS, JS, and SQL request forwarding so that we may get auto-complete suggestions and hover boxes.

**Comment by isc-bsaviano** [comment]
@Christian-Martinez1 Ok, I just wanted to clarify your request. InterSystems SQL varies significantly from the standard so forwarding Intellisense requests for that wouldn't be an improvement. For JS, CSS, Python and HTML I agree that request forwarding would be an improvement.

**Comment by Christian-Martinez1** [comment]
> @Christian-Martinez1 Ok, I just wanted to clarify your request. InterSystems SQL varies significantly from the standard so forwarding Intellisense requests for that wouldn't be an improvement. For JS, CSS, Python and HTML I agree that request forwarding would be an improvement.

Awesome, that would be absolutely useful if this could be added. Tried taking a look at the extension.ts file to see if I can do it myself but I don't have any experience with vs code extension development and wasn't too sure where to start.

**Comment by isc-bsaviano** [comment]
@Christian-Martinez1 This extension is maintained by InterSystems officially (unlike the main extension or server-manager) and we don't accept or solicit PR's so I will look at this when I have time. I have attempted adding this in the past but it's a lot of work.

**Comment by Christian-Martinez1** [comment]
I see, thank you for your time.

**Comment by isc-bsaviano** [comment]
@Christian-Martinez1 Quick update, I am actively working on this but I need https://github.com/microsoft/vscode/issues/151537 resolved before I will release it

**Comment by Christian-Martinez1** [comment]
@isc-bsaviano Awesome!!! Thank you so much mate, this will be fantastic for VS Code extensions like Prettier, etc.

**Comment by isc-bsaviano** [comment]
@Christian-Martinez1 No problem, happy to help! I don't use prettier so I'm not sure if what I implemented is going to help you use it for CSP files. My update to the README details what support was added:

https://github.com/intersystems/language-server/blob/6ec3a38c85f58a2694879223c685f810786010cd/README.md?plain=1#L62-L64
