### ISSUE TITLE
Allow "Go to symbol with line offset"

### ISSUE THREAD

**Issue by LogMull** [intersystems/language-server#230]
In Cache Studio, the hotkey ctrl+g would allow the user to go to a tag / label and optionally allow +/- line numbers.  VS Code allows for raw line numbers and the language server already allows going to symbols, which is great.  If it is possible, it would be very nice if something such as @method+25 could be entered to mimic what Studio allows.  This would be helpful when referencing error messages that indicate line offsets.

**Comment by isc-bsaviano** [comment]
@LogMull A community member wrote an extension that does exactly this, you should give it a try: https://marketplace.visualstudio.com/items?itemName=georgejames.gjlocate

**Comment by LogMull** [comment]
That is great, thank you for pointing that out.
