### ISSUE TITLE
Linting not working on *.mac file

### ISSUE THREAD

**Issue by ebromberg** [intersystems/language-server#231]
I can't seem to get some of the linting to work on mac file. Specifically, the References to local variables that are undefined.
I created a simple xEBTesting.mac file that looks like:
ROUTINE xEBTesting

B
 w $$ASK("test","y")
 i test=1 w "hi"
 q
ASK(question,dfault) {
 i debug w "debug"
 q 1
 }

But yet I do not get any warning about the variables test or debug being undefined. 
Shouldn't that warning occur? Or am I misunderstanding something?

**Comment by isc-bsaviano** [comment]
@ebromberg Variable tracking is handled by the Studio parsers and only works in classes.
