### ISSUE TITLE
Extension incorrectly prompts for InterSystems Server Credentials when using no authentication

### ISSUE THREAD

**Issue by xoxloviwan** [intersystems/language-server#248]
![image](https://user-images.githubusercontent.com/43066471/196427090-8996ffb1-9ad8-4dcb-9bf9-17fbe0835b83.png)

**Comment by isc-bsaviano** [comment]
@xoxloviwan If you're storing your credential securely using server manager version 3 then you need to consent to sharing them with the Language Server if you want to get intellisense features that require a server connection. If you aren't using that feature or you don't care about storing your credentials securely then you an put the password in your server definition inside `settings.json`. The [Server Manager README](https://github.com/intersystems-community/intersystems-servermanager#new-in-version-32---october-2022) contains more info on the new authentication provider.

**Comment by xoxloviwan** [comment]
I connect to my local dev server without any authentication as UnknownUser with Minimal Security, and this message showed on every opening cls or mac file. Even if connection has already established. How can I disable this?

**Comment by isc-bsaviano** [comment]
@xoxloviwan Do you see this for the `InterSystems ObjectScript` extension too?

**Comment by gjsjohnmurray** [comment]
@xoxloviwan based on your mention of Minimal Security and using unauthenticated access (i.e. the Unknownuser user) are you using the client-side mode of operation with an `objectscript.conn` definition looking like this?

```json
    "objectscript.conn": {
        "active": true,
        "host": "localhost",
        "port": 57772,
        "ns": "USER",
        "username": "UnknownUser"
    }
```

If so, please try adding an empty `password` property so it becomes:
```json
    "objectscript.conn": {
        "active": true,
        "host": "localhost",
        "port": 57772,
        "ns": "USER",
        "username": "UnknownUser",
        "password": ""
    }
```

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray What we need to do here and in the main extension is if the username is `undefined`, the empty string or "UnknownUser" (case insensitive) we shouldn't ask the auth provider for a password.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano based on my testing of how the main extension already handles `objectscript.conn` properties, I don't think any changes are needed in it. But LS does need the changes you describe.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Thanks for confirming that. I will make the changes here.

@xoxloviwan What OS and architecture are you using? I will send you a beta version of the extension so you can test the fix before I release it.

**Comment by xoxloviwan** [comment]
windows x64 and linux x64, I will try your advice with empty password...

**Comment by isc-bsaviano** [comment]
@xoxloviwan Here's a beta version of the Language Server for Windows x64. Please unzip it, install the VSIX and let me know if the popup goes away using your existing configuration.

[language-server-win32-x64-2.1.3-beta.1.vsix.zip](https://github.com/intersystems/language-server/files/9863348/language-server-win32-x64-2.1.3-beta.1.vsix.zip)

**Comment by xoxloviwan** [comment]
```
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-50-generic
Sandboxed: No

InterSystems ObjectScript v2.0.0
InterSystems Server Manager v3.2.1
InterSystems Language Server v2.1.2
```

I add this part to objectscript.conn
```
"username": "UnknownUser",
"password": ""
```
hint still stayed 'Connected as undefined'
Then restart VS Code
And hint change to  'Connected as unknownuser'

**Comment by xoxloviwan** [comment]
On Windows can test only tomorrow... Sorry

**Comment by isc-bsaviano** [comment]
@xoxloviwan That's fine. I can give you a linux build too, I just need to know if it's alpine linux or not.

**Comment by gjsjohnmurray** [comment]
So it seems that the empty password property workaround is successful, right?

**Comment by xoxloviwan** [comment]
Ubuntu 20.04

**Comment by isc-bsaviano** [comment]
@xoxloviwan Here's a linux build:

[language-server-linux-x64-2.1.3-beta.1.vsix.zip](https://github.com/intersystems/language-server/files/9863435/language-server-linux-x64-2.1.3-beta.1.vsix.zip)

**Comment by xoxloviwan** [comment]
> So it seems that the empty password property workaround is successful, right?

I seems that setting username as Unknown User worked too...

**Comment by xoxloviwan** [comment]
I remove from objectscript.conn username and password and install this v2.1.3-beta.1

Now this message is appearing only one time. After that I allowed it, pressed Enter in empty input line. And it doesn't ask more on switching file tabs.

**Comment by isc-bsaviano** [comment]
@xoxloviwan That sounds like an improvement. What extension caused the prompt? Since you were prompted for a password, I think that is from the main extension and not this one.

**Comment by xoxloviwan** [comment]
Intersystems ObjectScriptnow
![image](https://user-images.githubusercontent.com/43066471/197869205-002455de-00f1-4788-aad2-156d4803b491.png)

**Comment by isc-bsaviano** [comment]
Ok, so the beta version of this extension that I sent you fixed the problem. Thanks for confirming that.

**Comment by isc-bsaviano** [comment]
Yes that sounds reasonable, thanks for your help

**Comment by xoxloviwan** [comment]
On Windows I found that I have another user not UnknownUser. I press toggle close/open connection and it asked me 'allow' until I not press key (sign) symbol. Is it normally behavior? I found that in my
`C:\Users\hohlov\AppData\Roaming\Code\User\settings.json` was strings `"username":"hohlov"`, I deleted them. And then it suggested me login as UnknownUser if press Enter in empty input. After login as UnknownUser messages were disappered.

As result it works on Windows. But I don't understand how was it minded changing user if it will be need.

**Comment by isc-bsaviano** [comment]
@xoxloviwan That's the expected behavior. If you have a username, you need a password. If you don't, then it shouldn't prompt you. I think this is working now.

**Comment by xoxloviwan** [comment]
My question is only about the situation when I want to login as another username but the extention remembers the first input username. How can I do this?

**Comment by isc-bsaviano** [comment]
If you change the username setting in `objectscript.conn` or `intersystems.servers` then the extensions should recognize the change and switch to the new user. You an always reload the window after the switch to "force" the extensions to reload as well.
