### ISSUE TITLE
Hyperlink class description hover to full Documatic information

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#250]
https://github.com/intersystems/language-server/blob/bc02a4d1c42ee1c6bbf97d2e36934d51a2e6a0af/server/src/providers/hover.ts#L85

![image](https://user-images.githubusercontent.com/6726799/205334306-9032608c-c47e-4048-a0b4-bf437699c45f.png)

I suggest making `normalizedname` into Markdown that opens the corresponding page of Documatic on the connected server.

Doing this will fill a feature gap that currently exists between VS Code and Studio. In Studio the context menu on a classname offers an option to open its documentation.

The hovers for commands, functions, SVNs etc already provide a similar link, though they label it "Online documentation", put it at the bottom of the hover where it is easier to reach when the hover appears above the pointer (default), and link to the static doc site:

![image](https://user-images.githubusercontent.com/6726799/205335967-ca54cbea-daea-43dd-9cf3-df674fa8b4c9.png)

**Comment by isc-bsaviano** [comment]
Good suggestion @gjsjohnmurray. I'll look at it when I have some time.
