### ISSUE TITLE
Improve the TypeHierarchyProvider fallback behaviour

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#255]
1. Open a class.
2. If the cursor isn't at the start of the first line (because you previously opened this class and moved the cursor elsewhere), click at the start of the first line. This replicates the common case (you haven't been in this class recently).
3. From Command Palette run `Types: Show Type Hierarchy`.
4. The References view appears but reports "No results." 😞 

I suggest improving this function

https://github.com/intersystems/language-server/blob/0c9a45cf0fcf9704bc1a9f2925033170dc018b8d/server/src/providers/typeHierarchy.ts#L23

so that instead of returning `null` when the current cursor position doesn't identify a class we check that the `params.textDocument.uri` string names a .cls file, then derive the name of the class from the uri and behave as though the cursor was within the class name which follows the `Class` keyword at/near the top of the file.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Good suggestion.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I was able to fix this for most cases but if the cursor is on a blank line no results are returned before my `onPrepare` method is called.
