### ISSUE TITLE
Language Server Error on Dynamic Objects in Trigger Code

### ISSUE THREAD

**Issue by mdavidovichHst** [intersystems/language-server#259]
Hello, 

When using dynamic objects in triggers, an error is thrown by the language server when setting up the empty array:

![image](https://user-images.githubusercontent.com/103590728/217270453-0fa61466-9c93-4e61-8c20-cd89f6143649.png)

However, the code does compile and work correctly:

![image](https://user-images.githubusercontent.com/103590728/217270534-abe9cef3-939f-440a-a0b3-1f925410583e.png)

Can the language server recognize that an object is an object and a property in {} syntax is a property?

I think the workaround would just be to initialize the array using ##class(%Library.DynamicObject).%New()

Thanks!

MD

**Comment by isc-bsaviano** [comment]
@mdavidovichHst This is caused by the unique `{fieldname}` syntax that's supported in Triggers. I will look into correcting this.
