### ISSUE TITLE
Are HTML table elements being stripped when hover is created from class description?

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#264]
Our Deltanji source control adds tabular status information into the class description.

Example class:
```objectscript
/// HL7QS Update Rule
/// Business Process for HL7 Quick Start
/// Given an incoming ADT message, this rule calls a data transformation and forwards the message to the message router.
/// <!-- ;vc;
/// ;vc;    Object: isclearning.HL7QS.UpdateRule.CLS/HCAPP1.0
/// ;vc; Component: CLS.isclearning.HL7QS.UpdateRule
/// ;vc;  Location: HCAPP1.dev
/// ;vc; Date/Time: 02-Mar-23 08:48
/// ;vc;      User: johnm
/// ;vc; --><p>Deltanji status:<table id='vcm' border='1' style='{font-size: 0.7em;}'><tr><td>Object</td><td>isclearning.HL7QS.UpdateRule.CLS/HCAPP1.0</td></tr><tr><td>Component</td><td>CLS.isclearning.HL7QS.UpdateRule</td></tr><tr><td>Location</td><td>HCAPP1.dev</td></tr><tr><td>Date/Time</td><td style='white-space: nowrap;'>02-Mar-23 08:48</td></tr><tr><td>User</td><td>johnm</td></tr></table>
/// 
Class Foo.Bar
{

}
```

How it appears in Documatic:
![image](https://user-images.githubusercontent.com/6726799/222384091-1aea9564-9653-45a5-a8b9-3702f65c7ce2.png)

And in hover tip:

![image](https://user-images.githubusercontent.com/6726799/222384385-99b6da72-693e-459e-874c-79851c4be792.png)

I think adding this
```ts
turndown.keep(["table", "tr", "td"]);
```
after here
https://github.com/intersystems/language-server/blob/56d878babe7d4d2a421f381ba3433051955c3c8e/server/src/utils/functions.ts#L17-L19

might bring the hover tip into step with Documatic.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I think the best way to fix this is the use a [turndown plugin](https://www.npmjs.com/package/@joplin/turndown-plugin-gfm) to convert the table html to markdown. I will try that first.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano thanks for turning this round so quickly, and for releasing 2.3.1 to get it out there.

**Comment by isc-bsaviano** [comment]
Happy to help! Unfortunately neither approach shows borders for the table but this is still an improvement over 2.3.0 IMO.
