### ISSUE TITLE
Please permit passage of `<span>`  tags in hover text

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#265]
Similar to #264, please add `"span"` to this array:

https://github.com/intersystems/language-server/blob/622f9c9709d5170409b0aca5a83e36357233580e/server/src/utils/functions.ts#L20

I think it will allow class descriptions to include color styling in a way that propagates to the hovers, e.g.
```objectscript
/// <span style="color:#ff0000;background-color:#00ff00;">HL7QS Update Rule</span>
```

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'll do this but I would strong recommend against using colors in your styles. You can't know what theme the user has enabled so your text could become illegible.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano fair point re colors, though it can be mitigated by setting both color and background-color. And if #266 gets resolved it may be possible to create colored horizontal barcharts

**Comment by isc-bsaviano** [comment]
Do we really want to show bar charts in Hover/Completion/SignatureHelp documentation? That seems inappropriate and too complex for the purpose of those UI elements.
