### ISSUE TITLE
Preserve empty `<span>` elements in hover documentation

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#266]
Continuing from #265, VS Code permits a syntax for displaying codicons in the hover markdown. But turndown is removing the empty `<span>` element it relies on:

```objectscript
/// <p>This works, but displays an underline character I don't want: <span class="codicon codicon-source-control">_</span></p>
/// <p>This doesn't work (no codicon shows) because of turndown's 'blank' rule: <span class="codicon codicon-source-control"></span></p>
```
![image](https://user-images.githubusercontent.com/6726799/222746335-e0e11f8d-06f9-45bc-8644-c18708639116.png)

An (untested) change at this line might work:
https://github.com/intersystems/language-server/blob/83358d6f1f1aea08a4aef091519968f0489eb26f/server/src/utils/functions.ts#L18

```ts
 	const turndown = new TurndownService({
            codeBlockStyle: "fenced",
            blankReplacement: function (content, node) {
                return node.nodeName === 'SPAN' ? node.outerHTML : ''
            },
        });
```

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'm a little hesitant to make this change. I don't think we should encouraging people to put VS Code-specific HTML in Documatic. Any number of clients could be trying to render that HTML.

**Comment by gjsjohnmurray** [comment]
Yes, the mechanism I want to leverage here is VS Code-specific, but it will fall back harmlessly in other contexts (e.g. Documatic web browser).

**Comment by isc-bsaviano** [comment]
Since the empty span is harmless in Documatic I'll make this change.
