### ISSUE TITLE
Adopt `LogOutputChannel` API which finalized in VS Code 1.74

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#267]
See https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray The OutputChannel for this extension is handled by the `vscode-languageclient` module. If it adopts this API then we will as well.

**Comment by gjsjohnmurray** [comment]
OK, I have opened https://github.com/microsoft/vscode-languageserver-node/issues/1206
