### ISSUE TITLE
Javascript does not support Promise-based API (await, async, ...)

### ISSUE THREAD

**Issue by Taulim** [intersystems/language-server#269]
Some of the methods used by Promises are marked as *syntax error* by the language server.

Examples:
![image](https://user-images.githubusercontent.com/7851440/226356996-7f6b8f13-15cd-4ebe-8028-69ab0e18679e.png)

Versions: 

- Language Server: 3.2.1
- ObjectScript: 2.6.1-beta.6
- VSCode: 1.75.0 (Flatpak)

**Comment by Taulim** [comment]
Yes, the code is in a CSP file:

![image](https://user-images.githubusercontent.com/7851440/226369055-eed0ca22-e1bd-41cc-af7d-190513a9d076.png)


> I can look into adding support for this newer JS syntax but if it's a significant effort then it may not get done quickly, if ever.

I can understand.

Some of our pages make heavy usage of this syntax, so we cannot use the IDE hints to check for mistakes (e.g.: forget to close a curly-braces).
While we are planing to use external files for all our JS it will take quite some time due to how large the code-base is.

If you do look into it would it also fix the object / array destructuring?

```js
const { a, b } = getObject();
const [ a, ...rest ] = getArray();

function ({ a, b }) {
  console.log(a, b);
}
```

Thank you for the quick response!

**Comment by daimor** [comment]
How much CSP is in that CSP files?
would not be simpler to switch to plain HTML in VSCode?
You can redefine language detection for the file extension in the settings
```
    "files.associations": {
        "*.csp": "html"
    },
```
<img width="542" alt="image" src="https://user-images.githubusercontent.com/1212251/226542073-b068e247-8776-4a5a-a15b-8659779bf55e.png">

**Comment by Taulim** [comment]
Hi @daimor .

This would not work for the production.
They are normally huge files with many server methods and calls.

On the example I simplified it, only having the JavaScript code to remove noise.
