### ISSUE TITLE
%Id() in embedded SQL query throws language server error

### ISSUE THREAD

**Issue by mdavidovichHst** [intersystems/language-server#274]
When using embedded SQL are you supposed to be able to access `object.%Id() ` from a host variable?

`&SQL(select ID into :match from This.Table where Property=:object.pointer.%Id())`

Or is this an illegal move?  The language server doesn't seem to like it:

![image](https://user-images.githubusercontent.com/103590728/234056558-28f07cb5-e15d-46e9-a196-8af10fadbbf4.png)

**Comment by isc-bsaviano** [comment]
@mdavidovichHst Based on a quick reading of the [Embedded SQL docs](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSQL_esql#GSQL_esql_hvars), you can only use object properties, not method results, for Host Variables.

**Comment by mdavidovichHst** [comment]
@isc-bsaviano Thank you.  Embarrassed that I didn't read that closely.  Thanks for doing that and for your response.
