### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by sschenks** [intersystems/language-server#276]
Type: <b>Bug</b>

When opening an object script piece of code the following error is being reported in the output window.  This happens on all code in all namespaces on all servers defined.

TypeError: Cannot read properties of undefined (reading 'length')
    at c:\Users\sschenks\.vscode\extensions\intersystems.language-server-2.3.3-win32-x64\server\out\server.js:2:215916
    at Generator.next (<anonymous>)
    at o (c:\Users\sschenks\.vscode\extensions\intersystems.language-server-2.3.3-win32-x64\server\out\server.js:2:191079)
[Error - 8:36:17 AM] The InterSystems Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Extension version: 2.3.3
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (8.02GB free)|
|Process Argv|--crash-reporter-id 601e9cfe-fc93-4e4e-add3-aeccfb489ccd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30730053
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by isc-bsaviano** [comment]
Hi @sschenks, I just updated VS Code to 1.78.0 and version 2.3.3 is working fine for me. What error is in the `InterSystems Language Server` output channel? You may need to sort through some webpack'ed JavaScript code but there should be an error message.

**Comment by isc-bsaviano** [comment]
@sschenks Are your servers active/reachable? I looked at the code where this error occurred and it happened because a query returned an unexpected result.

**Comment by sschenks** [comment]
Brett,
Thanks for taking a look.  I am very new to trying to get VSCode setup for use with Intersystems.  I believe I have everything correct as far as I can tell.  I do see a connection to my server and I can see and edit code even after getting the language errors.

![VSCode_langueage_error](https://user-images.githubusercontent.com/36306658/236250991-955891c3-1dbf-40c3-be69-f66dcf4c42e0.png)

I only have one remote server defined.

**Comment by sschenks** [comment]
It happens on any class that I open.  I have found a really small/simple one.  Here is the txt:

Class AH.Scratch.Gzip Extends (%RegisteredObject, %ArrayOfDataTypes)
{

Parameter BLOCKSIZE As %Integer = 512;

ClassMethod Compact(Path As %String = "", gzip As %Boolean = 1, pFileName As %String = "") As %Stream.FileBinaryGzip
{
    
  set archive = ##class(%Stream.FileBinaryGzip).%New()
  Set tSC = archive.LinkToFile("/intersystemsdev/test/test.txt")
  $$$ThrowOnError(tSC)
  
  
  Set tSC = archive.%Save()
  $$$ThrowOnError(tSC)
  Do archive.%Close()
  
  return archive
}

}

**Comment by isc-bsaviano** [comment]
@sschenks Can you install the version of the extension found below and let me know if it works for you? To install, unzip it to get the .vsix file, then click and drag it into the extensions panel in VS Code. It will install it and then prompt you to reload your window.

[language-server-win32-x64-2.3.4-fix.276.vsix.zip](https://github.com/intersystems/language-server/files/11400002/language-server-win32-x64-2.3.4-fix.276.vsix.zip)

**Comment by sschenks** [comment]
Brett,
I believe that has fixed the issue.  I installed the new extension, reloaded, exited then opened VSCode again.  I was able to open classes now with no error.

Was this a major fix or something that just had not been encountered before?

**Comment by sschenks** [comment]
Thank you for looking into the issue so quickly and creating the fix.  If you want to investigate further we can always set up a meeting and do some screen sharing.

Thank you for your help.

**Comment by sschenks** [comment]
Brett,
After reverting back to the older version of extension I am getting the below results.
It is looking like a permissions issue somewhere.  Below is the trace from my normal ID and it shows an error.
When I log out and back in again with my other ID that is a %ALL id I do not get the error.
I thought that I had all of the permissions correct but I must be missing something.


[Show Response](http://ahlengtxpla098.evv1.ah-isd.net:2773/csp/bin/Systems/Module.cxw?CSPSYS=7httptrace_2&CSPSYSstime_short=May++4+14:25:57&CSPSYSrequest_id=17c0&CSPSYStoken=WLX8XZbmZp&CSPSYSn=15656711&CSPTKN=125583350518035017692088697491#ShowResponse)
POST /api/atelier/v5/AHREPORTS/action/query HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json
Cookie: CSPSESSIONID-SP-2773-UP-api-atelier-=008000000000WLX8XZbmZpQ2Rwt7OVm2OZPxtJD6PXHfhbbbdr; path=/api/atelier/; httpOnly; sameSite=strict; CSPWSERVERID=hzZhkCwQ; path=/; httpOnly;
User-Agent: axios/1.4.0
Content-Length: 161
Accept-Encoding: gzip, compress, deflate, br
Host: ahlengtxpla098.evv1.ah-isd.net:2773
Connection: close

{"query":"SELECT $LISTTOSTRING(Importall) AS Importall FROM %Dictionary.CompiledClass WHERE Name = ?","parameters":["AH.AHREPORTS.Custom.NameSpace.NSRoleSetup"]}
[Show Request](http://ahlengtxpla098.evv1.ah-isd.net:2773/csp/bin/Systems/Module.cxw?CSPSYS=7httptrace_2&CSPSYSstime_short=May++4+14:25:57&CSPSYSrequest_id=17c0&CSPSYStoken=WLX8XZbmZp&CSPSYSn=15656711&CSPTKN=125583350518035017692088697491#ShowRequest)
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Set-Cookie: CSPSESSIONID-SP-2773-UP-api-atelier-=008000000000WLX8XZbmZpQ2Rwt7OVm2OZPxtJD6PXHfhbbbdr; path=/api/atelier/; httpOnly; sameSite=strict;
Cache-Control: no-cache
Date: Thu, 04 May 2023 19:25:57 GMT
Expires: Thu, 29 Oct 1998 17:04:19 GMT
Pragma: no-cache
Set-Cookie: CSPWSERVERID=hzZhkCwQ; path=/; httpOnly;
Content-Length: 376

{"status":{"errors":[{"error":"ERROR #5540: SQLCODE: -99 Message: User AHIS.sschenks is not privileged for the operation","code":5540,"domain":"%ObjectErrors","id":"SQLCode","params":[-99,"User AHIS.sschenks is not privileged for the operation"]}],"summary":"ERROR #5540: SQLCODE: -99 Message: User AHIS.sschenks is not privileged for the operation"},"console":[],"result":{}}

**Comment by isc-bsaviano** [comment]
@sschenks Yeah, that's the error. If you're using a version lower than 2022.2/2022.1.1/2021.1.3, you need to execute the following query to give %Developer (or your exact user) permissions to query the %Dictionary tables. They are used extensively for things like hover, code completion and other intellisense features. You can also upgrade to newer version if that is possible.

```sql
GRANT SELECT ON SCHEMA %Dictionary TO %Developer
```

**Comment by sschenks** [comment]
Brett,
That got it.  We are currently running IRIS for UNIX (Red Hat Enterprise Linux for x86-64) 2021.1.2 (Build 338_0_21969U) 
So that issue would apply for sure.  We will be upgrading after a few other things are completed.
I have also put back the fix for the extension.  I believe that should take care of the issue now.

Thank you very much.

**Comment by isc-bsaviano** [comment]
No problem Steve, happy to help!
