### ISSUE TITLE
Too much logs when offline

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#277]
Is it really necessary to keep logging that, when we intentionally have no connection to the server?
`objectscript.conn.active = false`

<img width="1318" alt="image" src="https://github.com/intersystems/language-server/assets/1212251/5962def5-918b-4322-a4d5-9bc392e85e2c">

**Comment by isc-bsaviano** [comment]
I can consider removing the logging code for this specific case since an inactive server connection is likely intentional.
