### ISSUE TITLE
Incorrect bracket pairing in embedded SQL fragment

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#28]
![image](https://user-images.githubusercontent.com/6726799/96716527-0d5e2900-139d-11eb-93af-0a37bcc7f23e.png)

Extracted from https://github.com/intersystems-community/vscode-objectscript/issues/249#issuecomment-713516889

**Comment by isc-bsaviano** [comment]
Closing this issue because it requires changes to the LSP that are currently on the Backlog and seem unlikely to be implemented soon. See https://github.com/microsoft/language-server-protocol/issues/672
