### ISSUE TITLE
Issue handling PARTITION 

### ISSUE THREAD

**Issue by PeteOH** [intersystems/language-server#282]
ROW_NUMBER() OVER **(PARTITION BY field1 ORDER BY  field1, field2 DESC)** AS RowNum

The PARTITION BY brackets are not being handled by the VSCode Language Server. This is working on IRIS compiler.

**Comment by isc-bsaviano** [comment]
@PeteOH Can you share a screenshot of the issue please?

**Comment by PeteOH** [comment]
here are the screen shots of 2 issues when ROW_NUMBER() is then followed by
OVER (...)

[image: image.png]

[image: image.png]
*Peter O'Halloran*
M: +61 409 447 185
E: ***@***.***

**Comment by isc-bsaviano** [comment]
@PeteOH Thanks for the screenshots. This is a bug in our SQL parser. I have reported this internally to the correct person, but I can't guarantee that it will be addressed quickly. In the meantime, if you'd like to hide those syntax errors to avoid distraction you can use the `intersystems.language-server.diagnostics.suppressSyntaxErrors` setting.
