### ISSUE TITLE
Go to definition doesn't open git file 

### ISSUE THREAD

**Issue by zvondic** [intersystems/language-server#294]
We are using ISC Ensemble Cache for UNIX (Red Hat Enterprise Linux for x86-64) 2018.1.7 (Build 721U) Fri Mar 18 2022 22:01:43 EDT and VS Code on windows remote desktop. 
Git repository is located on Ensemble server and VS Code is connected by Remote SSH plugin to this repository. 
Problem is that go to definition (F12) doesn't open file from git repository but opens file from cache database which is disabled for editing. Is there any chance how fix this behavior?  When i want to edit any file i have to open it from explore and it is very non-productive.
![gotodefinition](https://github.com/intersystems/language-server/assets/5123917/98fcd375-4962-4676-aece-e86a1317e71d)

**Comment by isc-bsaviano** [comment]
@zvondic I need to know a little bit more about your workspace folder to detemrine the cause. The Langauge Server uses the vscode-objectscript extension to resolve a URI for a file name. That extension uses your `objectscript.export` settings to determine what the URI would be if you had exported the file using the extension and checks if that exists. If it doesn't then the server copy is used. It;s possible that your export settings don't reflect the structure of your workspace. If you have a `.code-workspace` file, can you post its contents here? If not, can you post the contents of your `.vscode/settings.json` file instead please?

**Comment by zvondic** [comment]
Hi Brett,
i found setting.json in c:\Users\xzvonicek\AppData\Roaming\Code\User\
and workspace.json
c:\Users\xzvonicek\AppData\Roaming\Code\User\workspaceStorage\ae5ee1a17d6a13d0c6ed13af94240448\
Thanks. Josef

st 25. 10. 2023 v 13:48 odesílatel Brett Saviano ***@***.***>
napsal:

**Comment by zvondic** [comment]
I am sending VS code  profile.

st 25. 10. 2023 v 18:06 odesílatel Josef Zvonicek ***@***.***>
napsal:

**Comment by gjsjohnmurray** [comment]
@zvondic attachments to emails sent to GitHub don't survive the journey. Please use the web interface to attach them to the issue.

**Comment by zvondic** [comment]
[workspace.json](https://github.com/intersystems/language-server/files/13169839/workspace.json)
[settings.json](https://github.com/intersystems/language-server/files/13169840/settings.json)
[zvoj.code-profile.json](https://github.com/intersystems/language-server/files/13169856/zvoj.code-profile.json)

**Comment by isc-bsaviano** [comment]
@zvondic I think the problem may be your `objectscript.export.folder` setting. If you want to represent the workspace root, use `""`, not `"."`.

**Comment by zvondic** [comment]
I changed but no success. :-(
![image](https://github.com/intersystems/language-server/assets/5123917/0725c043-372a-4238-9781-1300862f766c)

**Comment by isc-bsaviano** [comment]
@zvondic How did you get that workspace.json file? VS Code workspaces are .code-workspace files. I see that workspace.json file has a folder with the `vscode-remote` URI scheme. If your workspace is remote (that is, the URI scheme is not `file` for your local file system) then the main extension's code that tries to find the local file probably won't work.

**Comment by zvondic** [comment]
Yes, as i wrote in my first post. I don't have any workspace.json  file. Workspase  is placed on remote server, and files are served by ssh-remote plugin in VS code. The worspace.json which i sent is self-created by VS code. Goto-reference isn't work properly, that's why I asked for help.

**Comment by isc-bsaviano** [comment]
@zvondic I'm pretty sure that I correctly identified the issue in my previous comment. The main extension has a bunch of checks where it considers workspace folder with the scheme `file` to be local. This excludes your workspace folder, so it doesn't try to find a local copy of the file. We could make this check "NOT `isfs` or `isfs-readonly`" (our file system schemes) but I'm not sure if it would Just Work, of if there would be unintended consequences. I think this requires more discussion amongst the group that manages these extensions. Even though this is an issue with the main extension, I'll leave it open here since anyone can easily view the comment history. Thank you for reporting this.

**Comment by isc-bsaviano** [comment]
@zvondic Please follow the linked issue for updates
