### ISSUE TITLE
#dim var as class = object.method() labeled as syntax error

### ISSUE THREAD

**Issue by mburstinisc** [intersystems/language-server#30]
The following code:

In the following block of code:

	s stmt = ##class(%SQL.Statement).%New()
	s sql = "select TestID, fINT1, fVARCHAR1 from a.tab_1 where fINT1 %inlist ? and TestID in (35,122,1,153)"
	s il = $lb(1,-8989, 31,4123)
	s st = stmt.%Prepare(.sql)
	#dim strs as %SQL.StatementResult = stmt.%Execute(il)

The line:

	#dim strs as %SQL.StatementResult = stmt.%Execute(il)

is properly colorized but the strs is underlined with squiggly line and listed as a "Syntax error" from InterSystems Language Server.

**Comment by mburstinisc** [comment]
<img width="925" alt="dim syntax error" src="https://user-images.githubusercontent.com/17569403/96734308-696a8280-1388-11eb-97ac-5a185e3446d7.png">

**Comment by isc-bsaviano** [comment]
I copied your code block into a test method and didn't get a syntax error. Can you post the entire method so I have the full context?

**Comment by mburstinisc** [comment]
Method TestInList()
{
	s script = "inlist.sql"
	s method = ##expression(""""_%methodname_"""")
	d ..runTest(script, method)
	
	s runtest = ..isTestWhitelisted($classname() _ "." _ method)
	if (runtest=0) {
		quit
	} 

	if (..shouldTestRun() = 0) {
		d $$$AssertSkipped("shouldTestRun = 0")
		quit
	}
	
	new $namespace
	s $namespace = ..master
	
	d $system.SQL.Purge()
	
	s stmt = ##class(%SQL.Statement).%New()
	s sql = "select TestID, fINT1, fVARCHAR1 from a.tab_1 where fINT1 %inlist ? and TestID in (3,12,1,15)"
	s il = $lb(1,-8989)
	s st = stmt.%Prepare(.sql)
	#dim strs as %SQL.StatementResult = stmt.%Execute(il)
	s cn1 = ""
	s st = stmt.%GetImplementationDetails(.cn1)
	d $$$AssertEquals(1, st, "Got implementation details for " _ sql)
	d $$$LogMessage(cn1)
	
	k stmt, strs
	
	s stmt = ##class(%SQL.Statement).%New()
	s sql = "select TestID, fINT1, fVARCHAR1 from a.tab_1 where fINT1 %inlist ? and TestID in (35,122,1,153)"
	s il = $lb(1,-8989, 31,4123)
	s st = stmt.%Prepare(.sql)
	#dim strs as %SQL.StatementResult = stmt.%Execute(il)
	s cn2 = ""
	s st = stmt.%GetImplementationDetails(.cn2)
	d $$$AssertEquals(1, st, "Got implementation details for " _ sql)
	d $$$LogMessage(cn2)
	
	d $$$AssertEquals(cn1, cn2, "Cached queries are the same")
}

There are obviously quite a few methods and properties which this calls out to in a class that this class extends.  

I'm new to using Github and didn't see a place for version numbers, etc but:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Intersystems server manager: v1.0.0
InterSystems ObjectScript: v1.0.1
InterSystems Language Server: v1.0.0

**Comment by mburstinisc** [comment]
Doh!  It ends up that I was over-aggressive in my copy/paste and #dimed the variable twice
