### ISSUE TITLE
Add support for property Aliases

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/language-server#307]
I don't see Intellisense for property aliases. For example:

```
Property Name As %String(MAXLEN = "") [ Aliases = {SourceDirectory} ];
```

For the above, I would expect intellisense/autocompletion for both the Name and SourceDirectory property of the class.

Version info:

IRIS: IRIS for UNIX (Apple Mac OS X for x86-64) 2023.1.2 (Build 450_0_22983U) Mon Dec 18 2023 19:24:32 EST
Language Server: 2.4.3
VS code:
Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 22.6.0

**Comment by isc-bsaviano** [comment]
I can look into this but TBH I've never seen this before and I'm not why you'd ever want to use it.

**Comment by isc-kiyer** [comment]
Thanks! I had never seen it before either until today but is in a shared codebase so not my choice.
