### ISSUE TITLE
Enhance Intellisense on %New

### ISSUE THREAD

**Issue by baasvancodeza** [intersystems/language-server#308]
Type: <b>Feature Request</b>

When creating an instanceof a class using %New, and the class has a %OnNew method defined with arguments, the arguments are not shown on the popup containing the argument names and types.
Technically this is correct, but it would be nice for  %New specifically to pull the information from %OnNew

Extension version: 2.4.3
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by isc-bsaviano** [comment]
Interesting suggestion. I can look into it.
