### ISSUE TITLE
hovertext incorrect for methods with default values with $lb()

### ISSUE THREAD

**Issue by mburstinisc** [intersystems/language-server#311]
If I have a method defined as:
Method runBigVector(colCount As %Integer, vecsize As %Integer, rowcount As %Integer = 50, types As %List = {$lb("int", "double", "decimal", "string")}, skipLevel As %Integer = 0)

When I start typing in to calling that method, the types %List causes the hover text for filling in the rest of the signature:
![image](https://github.com/intersystems/language-server/assets/17569403/87dbb4b4-fd1d-48c5-bc4f-83a42315ab63)

Note that from that image, you can see that I typed in 25 as the rowcount value, then 2 commas.  The first comma advanced the hovertext to types, but the next comma (to accept the default value for types) advanced the hovertext to "double" being highlighted instead of skipLevel.

**Comment by isc-bsaviano** [comment]
Thanks for the screenshot.

**Comment by isc-bsaviano** [comment]
@mburstinisc I just tried to reproduce this using the latest version (2.4.3) and I can't. Are you on the latest version? If so, can you send me the exact class you're using so I can test with it?
