### ISSUE TITLE
Suggestion: Warn on use of SQL Reserved Words in class names / properties.

### ISSUE THREAD

**Issue by chadsevertson** [intersystems/language-server#315]
The list of [SQL Reserved Words](https://docs.intersystems.com/iris20241/csp/docbook/DocBook.UI.Page.cls?KEY=RSQL_reservedwords) is extensive. Currently, the first time you may notice such an issue is when you attempt to query the table. You'll receive an error similar to the following: `IDENTIFIER expected, reserved word GLOBAL found ^SELECT * FROM Integrity . GLOBAL`

It would be helpful to highlight any reserved words in class names and property names. I'm not sure about how the limits apply to Methods with or without [SQLProc].

**Comment by isc-bsaviano** [comment]
I think this is a good suggestion and that I should explore this. There are two parts of this that could be tricky though:
* Do we support classes that are an indirect subclass of `%Persistent`? That's not hard to do technically but diagnostics are requested a lot, so dding another REST request could entail a performance hit.
* We need to not show the diagnostic if there's a `SqlTableName` or `SqlFieldName` that overrides the class/property name.
