### ISSUE TITLE
Inherited %%OID members display ahead of baseclass members

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#325]
This logic (which occurs in several other places in the same file) doesn't cater for how the member names of inherited property `%%OID` and its methods `%%OIDGet` and `%%OIDSet` are wrapped in doublequotes, meaning they sort ahead of baseclass members, whose sortText is prefixed  with `##`.

https://github.com/intersystems/language-server/blob/bd0c373e6e9d22564c7240104bcd31bdca1bb243/server/src/providers/completion.ts#L1115

A simple solution is probably to use `!!` as the sortText prefix instead.

(arose from https://community.intersystems.com/post/modifying-visual-studio-code-code-assist-results)

**Comment by isc-bsaviano** [comment]
Thanks for reporting this John. We definitely don't want those appearing first.
