### ISSUE TITLE
Better handling of "Routine XYZ does not exist in namespace" Intellisense warning

### ISSUE THREAD

**Issue by CacioGit** [intersystems/language-server#328]
Type: <b>Bug</b>

Assume the simple code extract:
---
 S nsp=$NAMESPACE
 ZN "%SYS" 
 S res=$$BACKUP^DBACK("","F","Full Backup",cbkDir_"FullDBList_"_$ZD($H,8)_".cbk",,"./Backup/FullDBList_"_$ZD($H,8)_".log","NOISY",,,)
 ZN nsp
---

Intellisense is marking the call to ^DBACK as an issue, as the routine doesnt exist in the current namespace.
I did not find any way to tell VSCode to aknoledge the "false positive" alert and ignore it.

Extension version: 2.5.0
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Related: #77, #177, #206

**Comment by isc-bsaviano** [comment]
@CacioGit Thanks for reporting this, I will try to reproduce it. There isn't a way to tell VS Code to "ignore" a specific problem, but you can turn off routine existence diagnostics temporarily if that would help. The setting is `intersystems.language-server.diagnostics.routines`.

**Comment by CacioGit** [comment]
intersystems.language-server.diagnostics.routines did the trick and removed the quite annoying "1 issue with this code" warning flag.

From the previous discussions on similar issues, I can see how it is not really that easy to implement such a logic within the Intellisense's module.

Feel free to close the issue, unless the multiple reports of a similar request may trigger considering possible workarounds/solutions.

Thank you John and Brett.

**Comment by isc-bsaviano** [comment]
@CacioGit This should work due to my fix for #312. My fix is probably buggy when switching namespaces. I will investigate.

**Comment by CacioGit** [comment]
Perfect,
thank you Brett, I really appreciate your work in fixing this so quickly!
I will test the beta build later today and drop a comment here if it doesn't resolve the issue on my VSCode instance.

**Comment by isc-bsaviano** [comment]
@CacioGit My original fix was incomplete, so I committed an updated one. The properly fixed version is [here](https://github.com/intersystems/language-server/releases/tag/v2.5.1-beta.3).
