### ISSUE TITLE
Requests to the API does not use cookie

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#33]
Original issue report
https://github.com/intersystems-community/vscode-objectscript/issues/416

**Comment by BerndMueller** [comment]
this bug should be considered critical since this is affecting licensing and general service availability.

**Comment by daimor** [comment]
@BerndMueller You can temporarily disable the Language server extension, for a while, until the issue will be solved.

**Comment by BerndMueller** [comment]
i already tried that but it does not work for me. With that extension disabled it cannot even connect to the IRIS/CE anymore.

**Comment by daimor** [comment]
Are you sure, that you disable the right extension?
The main extension is InterSystems Objectscript, connection controlled there, and not in Language Server, where are just some additional features.
![image](https://user-images.githubusercontent.com/1212251/96875022-6dc59700-147f-11eb-9132-ac5dc8e5cfb3.png)

**Comment by BerndMueller** [comment]
yes, i am sure. It does not work for me anymore. It starts back working after enabling it again.

**Comment by daimor** [comment]
And after disabling language server, reload is required

**Comment by BerndMueller** [comment]
i did a reload. I wondering that it works for you. By the way, i have v1.0.1 objectscript extension.

**Comment by gjsjohnmurray** [comment]
@BerndMueller when you were able to connect did you get prompted for username and/or password? Or have you put username in the `intersystems.servers` connection definition and used the Server Manager command to put your password into your keystore?

Another thing to try after disabling Language Server is to close your VSCode workspace and create a fresh one. There's some client side caching that might be affecting you.

**Comment by BerndMueller** [comment]
Hi Brett, you are correct. I didn't click on "later". Doing this will make the main-extension working with the language-server extension disabled. Thanks for this and fixing this 👍

**Comment by isc-bsaviano** [comment]
@BerndMueller Version 1.0.1 does not fix this issue. I will submit a new PR this morning that contains the proper fix. Please look out for version 1.0.2

**Comment by theflyingape** [comment]
I can confirm **1.0.1** did not fix the issue for us either.  It started out promising, but on the next reload, repeated challenges until our AD disable login policy kicks-in, ugh.

**Comment by daimor** [comment]
It looks like the main extension has issues with cookies as well. I'm working on the fix
