### ISSUE TITLE
Intellisense for Defines is limited

### ISSUE THREAD

**Issue by stefanc82** [intersystems/language-server#338]
Intellisense does not support defines from include files properly.

It does not bring up the define names defined in the include file when typing triple dollar and the start of the define name.

Also, when hovering over a define or pressing the control key when it is used in embedded SQL, it does not provide the link to click or show the value of the define.

**Comment by isc-bsaviano** [comment]
@stefanc82 Only macro definitions that follow a `///` line are shown in completion lists. This is a feature of the IRIS server and is documented [here](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GCOS_macros#GCOS_macros_commentsassist). This extension doesn't currently support macro intellisense in Embedded SQL, but I can look into that.
