### ISSUE TITLE
Intellisense for Ouput parameters

### ISSUE THREAD

**Issue by WolfenGames** [intersystems/language-server#345]
Hi all,

I saw the lovely addition recently of better support to the return types from functions, which was amazing.
I was wondering if this could also be included for Output parameters as well?
Attached is an image to show a very simple case that I came up with.

![image](https://github.com/user-attachments/assets/94f568cc-d931-4dc0-8141-0f6a48a2628d)

If it's not possible, or too complex I will also understand, but it could be a nice addition.

Edit to fix example.

**Comment by isc-bsaviano** [comment]
This is a logical next step.
