### ISSUE TITLE
Autocompletion includes thousands of irrelevant entries

### ISSUE THREAD

**Issue by MichelSimar** [intersystems/language-server#346]
Hi All,

We are working with a large legacy codebase written in ObjectScript, and we've encountered a frustrating issue with the autocomplete feature in VS Code.

Currently, autocomplete suggests variables that are not in scope, which leads to counterproductive behavior.

At this point, autocomplete provides suggestions from all local variables present in our entire codebase, which spans a million lines of code. This includes variables that are not in scope within the current context.

This issue is particularly problematic when common single-character variables such as d and q appear in suggestions. It becomes cumbersome to type statements ending with uppercase letters such as D or Q because the autocomplete interferes.

![vscode](https://github.com/user-attachments/assets/72264d0a-582e-47a4-909c-b64c0302d100)

Is there a way to configure the autocomplete to only suggest variables that are currently in scope?

Best regards,
Michel, Simar automatisering

**Comment by isc-bsaviano** [comment]
@MichelSimar These suggestions are coming from VS Code itself, and not from this extension. There may be a VS Code setting to turns those off but I'm not sure.
