### ISSUE TITLE
Unexpected new dialog during password retrieval using Server Manager authprovider

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#356]
Type: <b>Bug</b>

Happened after today's update.

![image](https://github.com/user-attachments/assets/50a5e819-85cb-4020-9aa5-87225f7a2511)

On some pathway `serverSpec.name` is apparently `undefined` when serverManagerApi.getAccount(serverSpec) is called.

Extension version: 2.6.4
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray What did you to to produce that dialog?

**Comment by isc-bsaviano** [comment]
Here's what `serverSpec` contains when I follow your steps:

```json
{
    "serverName": "iris2",
    "active": true,
    "scheme": "http",
    "host": "localhost",
    "port": 52773,
    "pathPrefix": "/iris",
    "username": "_SYSTEM",
    "namespace": "INTEROP",
    "apiVersion": 8,
    "serverVersion": "2025.1.0"
}
```

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray The issue seems to be that the Language Server uses `serverName` for the server's name, while the Server Manager expects `name`. I will fix this.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Can you try the 2.6.5-beta.1 before I do another release? https://github.com/intersystems/language-server/releases/download/v2.6.5-beta.1/language-server-2.6.5-beta.1-win32-x64.vsix

**Comment by daanvd** [comment]
It's working for me. I had the same issue

**Comment by isc-bsaviano** [comment]
Thanks @daanvd, the new release will be out shortly.

**Comment by gjsjohnmurray** [comment]
Thanks for the speedy fix @isc-bsaviano. Sorry I wasn't able to beta-test it as I was on a call, but I have updated to the new 2.6.5 release and no longer have the issue.
