### ISSUE TITLE
Is it possible to switch off absent classes detection?

### ISSUE THREAD

**Issue by AlexeyM64** [intersystems/language-server#36]
False positives that are being detected are associated with non-% system classes, e.g.:

set sc=##Class(Config.Databases).Get(pDB, .prop)

It's virtually impossible to recognize that the current namespace was preliminarily switched to "%SYS", so maybe it worth introducing a setting whether to consider "absent classes" problematic or not.
By the way, you already have a similar setting for MACs and INCs.

**Comment by isc-bsaviano** [comment]
@AlexeyM64 Can you describe the exact steps you followed to get the false negative? The LS will recompute your diagnostics if you change the namespace while the document is open so if you go from not %SYS -> %SYS, the diagnostic will go away.

**Comment by AlexeyM64** [comment]
> if you change the namespace while the document is open
I don't see a way how can change the current namespace in the VS Code.
Even if I could, I would get much more diagnostic about other classes that were left in my "home" namespace.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano, imagine writing code in the USER namespace that uses a class that only exists in the %SYS namespace. At edit time the target class can't be found. But the code you wrote swaps to the %SYS namespace just before the bit that uses that class. Then it swaps back later.

@AlexeyM64 did you close this issue intentionally? If not, please reopen it.

**Comment by gjsjohnmurray** [comment]
OP has reopened as #40

**Comment by gjsjohnmurray** [comment]
@AlexeyM64 sorry, I assumed the repo would allow the OP to reopen their issue. @isc-rsingh if you agree that it's reasonable to allow people to reopen their own closed issues here please make the config change on this repo.

**Comment by isc-rsingh** [comment]
I don't have permissions for that. Seems difficult in this organization.
