### ISSUE TITLE
No intellisense when VS Code uses remote connection to an Ubuntu OS installed on WSL2 in Windows

### ISSUE THREAD

**Issue by jtsalten** [intersystems/language-server#38]
Hi, I normally work with two basic environments. Windows and Linux, so I have at least 2 instances running always, one in my Windows host and the other one in my Ubuntu host running on WSL2. I can connect to both of them without problems, with VS Code, Studio, Atelier,...

The issue is that the new features that come with intersystems-community.vscode-objectscript and intersystems.language-server extensions doesn't seem to work when dealing with my IRIS installed on Ubuntu. 
I've uninstalled all InterSystems/ObjectScript related extensions in Windows and also in Ubuntu, and installed again, just in case, But intellisense features that work when developing with IRIS instance in Windows doesn't work it's counterpart in Ubuntu.

**Comment by daimor** [comment]
Looks like a duplication of a recently reported issue #32

**Comment by isc-bsaviano** [comment]
@jtsalten What error messages do you get when you try to connect the IRIS on Linux? Is the VSCode installation also on Linux, or is it installed on Windows?

**Comment by jtsalten** [comment]
VSCode is installed in Windows but is able to run agains remote hosts, as the Linux distros you can have running on WSL2 on Windows. In theory it should be the same. You also decides which extensions you install when using each Remote connection... I've installed InterSystems/ObjectScript extensions for local and for Remote-WSL.

These are the messages that I got when connected to Ubuntu instance using Remote-WSL connection:
free(): invalid pointer
[Info  - 5:49:28 PM] Connection to server got closed. Server will restart.
free(): invalid pointer
[Info  - 5:49:28 PM] Connection to server got closed. Server will restart.
free(): invalid pointer
[Info  - 5:49:28 PM] Connection to server got closed. Server will restart.
free(): invalid pointer
[Info  - 5:49:28 PM] Connection to server got closed. Server will restart.
free(): invalid pointer
[Error - 5:49:28 PM] Connection to server got closed. Server will not be restarted.

**Comment by isc-bsaviano** [comment]
@jtsalten Are you launching VSCode in the Ubuntu subsystem? I'm not familiar with WSL2 but if you're launching VSCode in Linux like in this blog post (https://code.visualstudio.com/blogs/2019/09/03/wsl2#_wsl-2-and-visual-studio-code) then I think this is the same bug as #32

**Comment by jtsalten** [comment]
Yes. I'm launching VS Code with "code ." from Ubuntu distro in WSL2. That just open VS Code installed on Windows with Remote-WSL extension that automatically connects with Ubuntu. It should work, shouldn't it? Till now I've been doing so without problems... but perhaps something goes wrong w.r.t IS Language Server and that Extension...

**Comment by isc-bsaviano** [comment]
@jtsalten The Language Server is spawned as a separate process by the main VSCode process so if that's being spawned on the Linux subsystem then you're likely experiencing the same issue as #32.

**Comment by gjsjohnmurray** [comment]
Maybe worth experimenting with the `remote.extensionKind` setting that's documented [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location).

**Comment by gjsjohnmurray** [comment]
@jtsalten do you still see this issue with the latest Language Server (1.1.4)?

**Comment by jtsalten** [comment]
> @jtsalten do you still see this issue with the latest Language Server (1.1.4)?

Hi John. Sorry for late response. Since I found these issues I back to VS Code in windows even to deal with my IRIS instances on Linux... but I've tested again running VS Code from Linux (WSL2 - Ubuntu) and now it works with Language Server 1.1.6.
Thanks,
Salva

**Comment by isc-bsaviano** [comment]
@jtsalten Glad to hear that the issue is resolved
