### ISSUE TITLE
embeded &js syntax

### ISSUE THREAD

**Issue by MaxAbrahams** [intersystems/language-server#39]
i think this is all valid JS, just some examples. Class compiles fine with language-server disabled.

I can provide much more detail and use cases, let me know. 
![1](https://user-images.githubusercontent.com/11665665/97019723-ab2d3180-151e-11eb-8255-ce81b5fd67b7.jpg)
![2](https://user-images.githubusercontent.com/11665665/97019724-ab2d3180-151e-11eb-9979-24c3b4f85a6d.jpg)
![3](https://user-images.githubusercontent.com/11665665/97019725-ab2d3180-151e-11eb-9e6c-5b594f5fba88.jpg)

**Comment by isc-bsaviano** [comment]
What version of the vscode-objectscript extension are you using?

**Comment by MaxAbrahams** [comment]
1.02

**Comment by isc-bsaviano** [comment]
@MaxAbrahams What's the error message that you're getting in the 3rd image? Can you paste your code here so I can attempt to reproduce this?

**Comment by MaxAbrahams** [comment]
Hi Brett; are you still looking for code samples? I know we talked via IM after the above message but just wanted to follow up.

**Comment by isc-bsaviano** [comment]
@MaxAbrahams Andy is working on this issue now and is making progress. It brought to light some shortcomings of our JS parser that are taking some time to fix.
