### ISSUE TITLE
Is it possible to switch off absent classes detection? (2)

### ISSUE THREAD

**Issue by AlexeyM64** [intersystems/language-server#40]
(I erroneously closed the issue under the same topic, sorry for it)

False positives that are being detected are associated with non-% system classes, e.g.:

set sc=##Class(Config.Databases).Get(pDB, .prop)

It's virtually impossible to recognize that the current namespace was preliminarily switched to "%SYS", so maybe it worth introducing a setting whether to consider "absent classes" problematic or not.
By the way, you already have a similar setting for MACs and INCs.

I was asked if I can change the current namespace while the document is opened to %SYS to avoid such messages.
I doubt whether it's a reasonable idea:
- How can I change the current namespace in VS Code?
- Even if I could, I'd get much more error messages about other classes from my "home" namespace.

**Comment by isc-bsaviano** [comment]
@AlexeyM64 I misunderstood your original issue. John's comment on the original issue (https://github.com/intersystems/language-server/issues/36#issuecomment-715444805) clarified this for me. Yes, if you change the namespace in the class via Set $NAMESPACE or ZN, you will get imperfect diagnostics. I can add a configuration option to turn class existence diagnostics off like for routines.
