### ISSUE TITLE
Go to Definition opens file on remote when fileext is in uppercase

### ISSUE THREAD

**Issue by Nemesis1990** [intersystems/language-server#42]
When the local files are saved with uppercase file extension (e.g. Class.CLS) the extension opens the remote file with Class.cls in read-only mode when I use "Go to Definition":

![image](https://user-images.githubusercontent.com/6547466/97141176-86270180-175e-11eb-88ac-dd8862aa9a6a.png)

Language-Server Version: 1.0.2
Objectscript-Version: 1.0.3

**Comment by isc-bsaviano** [comment]
@Nemesis1990 As currently implemented, go to definition will always open the remote version of the file if the definition isn't in the current file.

**Comment by Nemesis1990** [comment]
Ok. No Problem. But that's not working when the definition is in the current file (probably file extension):

This is a local file I opened with a definition in the same file:

![image](https://user-images.githubusercontent.com/6547466/97289292-49830500-1847-11eb-8e01-bbed50c0efbb.png)

Go to Defintion opens server file:

![image](https://user-images.githubusercontent.com/6547466/97289431-76371c80-1847-11eb-92f0-7e87cac3a550.png)

I found this hardcoded '.cls' here:

 https://github.com/intersystems/language-server/blob/ddae393f3337bed58e113dad08276476acd7e0b8/server/src/server.ts#L4153

Maybe something like this helps?:

```typescript
function getFileExtension(uri: vscode.uri, default: string = '.cls'): string {
    const reg = /(?:\.([^.]+))?$/
    return reg.exec(uri.fspath)[1] || default
}
```

```typescript
const ext = getFileExtension(params.textDocument.uri);
const newuri = await createDefinitionUri(params.textDocument.uri,originclass, ext);
```

I can't test it because I somehow can't compile my fork of this project :(

**Comment by isc-bsaviano** [comment]
@Nemesis1990 I misspoke, even for class members that are in the same class the virtual version of the class will be opened. The only definitions that won't open a virtual file are go to definitions on macros or routine labels that are defined in the current class. Sorry for the confusion. I don't think that there's a bug here because simple changing the case of the file extension wouldn't change whether it's a virtual or local file URI.

**Comment by Nemesis1990** [comment]
Ah ok. No Problem.

**Comment by isc-bsaviano** [comment]
@Nemesis1990 Thanks for reporting anyways. If you think that opening the definition in the local file if it exists is an enhancement that would be worth considering please file it as another issue. I think this one can be closed unless you have more evidence of a bug.

**Comment by Nemesis1990** [comment]
Can be closed. I don't think it's that important atm

**Comment by gjsjohnmurray** [comment]
See also #45
