### ISSUE TITLE
New messages about debugger listening

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#51]
Issue Type: <b>Bug</b>

A couple of messages in the LS output channel that I don't recall seeing prior to 1.0.4
```
Debugger listening on ws://127.0.0.1:6009/eb8cd893-b7eb-4c03-82ee-ef434748e328
For help, see: https://nodejs.org/en/docs/inspector
```

Extension version: 1.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isc-bsaviano** [comment]
I'm pretty sure this was always there

**Comment by gjsjohnmurray** [comment]
OK. Any downside to having production build of LS do this on everyone's machines?

**Comment by isc-bsaviano** [comment]
I have no idea. That's not coming from any settings that I configured manually.

**Comment by daimor** [comment]
It may happen if you run ObjectScript extension under debugging, and Language-Server switch on debugging as well.

**Comment by isc-bsaviano** [comment]
Is this actually a bug?

**Comment by daimor** [comment]
No, for me it looks like this works as it supposed to be

**Comment by gjsjohnmurray** [comment]
@daimor is right. I was debugging the vscode-objectscript extension at the time. Closing this issue.
