### ISSUE TITLE
Request textDocument/documentSymbol failed with message: Cannot read property 'p' of undefined

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#52]
Issue Type: <b>Bug</b>

Create this test class:

```
Class YJM.Class1
{

Method x()
{
    quit
}

Property foo As %String;

}
```
Put your cursor at the end of the property definition line, after the semicolon.

Backspace to remove the contents.

When you delete the first character of the property name (i.e. the f), expect to see this message in Language Server's output channel:
```
[Error - hh:mm:ss] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'p' of undefined
  Code: -32603
```

Extension version: 1.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray What should the expected behavior be when you have improperly formatted UDL? Return all DocumentSymbols computed until you hit the error?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I followed your steps but didn't get an error when I deleted the "f" in "foo". The request completed successfully and the "Property" DocumentSymbol was still there, just without the "foo" label.

**Comment by gjsjohnmurray** [comment]
Try it with this one:
```
Class YJM.Class2
{

Property Foo As %String;

Method Method1()
{
    quit
}

}

```

Again, delete backwards from the end of the Property line.

Here's what I see:

![junk](https://user-images.githubusercontent.com/6726799/97632278-34b29700-1a2a-11eb-9684-407678e78ec8.gif)

This class is opened direct from the server using isfs.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I can reproduce it now. I'll fix this for the next version
