### ISSUE TITLE
Become a FoldingRangeProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#53]
Issue Type: <b>Feature Request</b>

Currently the vscode-objectscript extension does this, but LS should be able to do an even better job.

Extension version: 1.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

Checklist (will be updated by @isc-bsaviano as new ideas are added and old ones are completed):

- [X] UDL documentation comments
- [X] COS documentation comments (/// in first column)
- [X] XML tags in XData blocks
- [X] Storage XML tags
- [X] COS preprocessor code blocks (#ifdef etc)
- [X] Multi-line macro definitions (using ##Continue)
- [X] Dotted Do blocks
- [x] Embedded code blocks (&sql,&html,&js)
- [X] %DynamicObject/%DynamicArray
- [x] JSON in XData blocks
~~COS code blocks (if, else, try, catch, loops etc)~~ Will attempt in the future
- [x] Region markers (`#;#region` or `//#region` to start and `#;#endregion` or `//#endregion` to end)

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray What sort of things would you want us to fold? I just spoke with @isc-jamien and here's some initial ideas that we came up with:
- UDL documentation comments (already exists)
- COS code blocks (if, else, try, catch, loops etc)
- XML/Storage tags
- COS preprocessor code blocks? (#ifdef etc)
- JSON (in XData blocks, %DynamicObjects?)

Please post any other ideas here so we can keep a running list in one place

**Comment by isc-bsaviano** [comment]
More ideas:
- Multi-line macro definitions (using ##continue)
- Embedded code blocks (&sql,&html,&js)

**Comment by gjsjohnmurray** [comment]
- Dotted DO blocks (for old-school MUMPS programmers).

Also, keep in mind that though LSP supports  within-line folding, VS Code only supports linewise folding.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Ok that explains why my within-line folding wasn't working. I submitted an issue on the LSP page so I guess I should close that. Is there an issue on the main vscode repo that I can thumb up to get that resolved?

**Comment by isc-bsaviano** [comment]
Found and upvoted it: https://github.com/microsoft/vscode/issues/50840. Unfortunately it doesn't seem like we'll be getting this anytime soon so I'll modify my implementation to only provide folding ranges when it visually makes sense.

**Comment by mvhenderson** [comment]
For your consideration:

* When folding comment blocks allow folding any multiline comment 2+ lines. Right now it seems to only work with 6+ lines
* Consider simplifying folding logic to be indent/brace based, with some smarts around when brace on a newline and for comments.
* Add support for special decorators, eg `#; @begin-section` and `#; @end-section

Also ability to fold multi-line commands. A pattern I use frequently is to break `$Case` statements into multiple lines:

```
Set background = $Case(state,
   "ERROR":  "red",
   "WARNING": "yellow",
   :"green")
```

Note, and indent based folder would support this out of the box.

**Comment by isc-bsaviano** [comment]
@mvhenderson The LS folding range implementation will support folding documentation comments of 2+ lines. The other two bullet points should be posted as separate enhancement requests

**Comment by isc-bsaviano** [comment]
@mvhenderson I just added region markers to my to-do list above.
