### ISSUE TITLE
Fold based on indent

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#59]
Add ability to fold based on indent in addition to the scenarios outlined by #53

This would cover multiple scenarios such as conditional and loop blocks that use braces, as well as multiline commands (e.g. a `$Case` expression with a case per line).

Currently you could set `editor.foldingStragegy = indentation` but then the smart folding for comments and other stuff is lost.

**Comment by isc-bsaviano** [comment]
@mvhenderson Version 1.0.5 provides indentation-agnostic FoldingRanges for various COS and UDL code blocks. We will not be modifying our FoldingRangeProvider to be indentation-based.
