### ISSUE TITLE
Code completion needs to understand that %<classname> is shorthand for %Library.<classname>

### ISSUE THREAD

**Issue by joelsolon** [intersystems/language-server#64]
The code completion suggestions should be improved to include the shorthand way to refer to classes in the %Library package.

For example, If you type “property I as %Inte” you get a suggestion for %CPP.Integer which is not what you want; you just want %Integer but you have to pick %Library.Integer to get that one. The problem is that %Integer is acceptable and common, but the only way to get %Integer by itself is by typing it out. Same thing for %Numeric (you get %MV.Numeric as a suggestion). Same thing for %Date. Probably others...

**Comment by isc-bsaviano** [comment]
@joelsolon The LS populates that list using %Library.RoutineMgr_StudioOpenDialog, which returns the %Library classes in the long form. There isn't an option for me to change that in the query, so I'd have to filter that manually on the TypeScript side. I can do that, but not everyone may want that behavior. I'll discuss this with Jamie

**Comment by joelsolon** [comment]
It is standard behavior in Studio and that other IDE we used to support.

**Comment by isc-bsaviano** [comment]
Ok, I will change the behavior to match Studio.
