### ISSUE TITLE
Make code completion suggestions appear correctly within snippets

### ISSUE THREAD

**Issue by joelsolon** [intersystems/language-server#65]
If you type “prop” and accept the “property” snippet, after you type the name of the property and advance to the datatype, no automatic suggestions appear when you want to change it from %String by typing "%". Same thing happens with the “class method” snippet for the return type of the method. Even if you use Ctrl-Space you don’t get the correct list of suggestions. You have to use backspace and then space to re-trigger the correct list of suggestions.

I didn't check any other snippets for this behavior.

**Comment by isc-bsaviano** [comment]
@joelsolon This is a limitation of the way completions are triggered in VSCode. They're either triggered manually by keystroke (Ctrl-Space I think) or by typing a trigger character (space is one for ObjectScript). Since the snippet inserts the space for you, the completion doesn't trigger.

**Comment by joelsolon** [comment]
I see. Is it possible to make the Ctrl-Space **after** typing % and zero or more characters present the correct list?

**Comment by isc-bsaviano** [comment]
I need to do some more research on snippets to see what's possible. I didn't write them; they're coming from the main extension.

**Comment by gjsjohnmurray** [comment]
The default requirement to trigger completions manually when typing a value into a snippet placeholder is explained in https://github.com/microsoft/vscode/issues/107742#issuecomment-701181250

**Comment by isc-bsaviano** [comment]
Looks like there isn't any action that we can take here
