### ISSUE TITLE
"Class without super" snippet produces an error

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#68]
See https://github.com/intersystems-community/vscode-objectscript/issues/481

@joelsolon

**Comment by isc-bsaviano** [comment]
@joelsolon I haven't been able to reproduce this error. Is there anything else in the file when you do the snippet? Does the error pop up immediately after the snippet appears, or after you start typing the class name?

**Comment by joelsolon** [comment]
New file is completely empty. Error pops up immediately, every time. This is VS Code on a Mac (10.14.6).
I just tried every other snippet available in an empty file (from a to z) and none of them cause this problem except for this one.

**Comment by isc-bsaviano** [comment]
@joelsolon Ok I see it now. I had to roll back to version 1.0.4. Using by beta build of 1.0.5, this error doesn't appear. One of my fixes for another bug must have fixed this as well. I'll leave the issue open for now and once 1.0.5 is out you can revisit this issue and close it if you're satisfied with 1.0.5.

**Comment by isc-bsaviano** [comment]
@isc-solon Version 1.0.5 is now live. Can you please verify that this issue has been fixed and if so, close it?

**Comment by isc-solon** [comment]
Looks good to me
