### ISSUE TITLE
Override method command

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#71]
From https://github.com/intersystems-community/vscode-objectscript/issues/118

@mvhenderson

**Comment by gjsjohnmurray** [comment]
The Java extension does it by contributing a Code Action which operates like this:

https://code.visualstudio.com/docs/java/java-refactoring#_overrideimplement-methods

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray That's a good way of doing it. My original idea was to do it through completion: when you type Method/ClassMethod and hit space, you get a bunch of suggestions for Methods/ClassMethods that are inherited from your superclasses and hen you select one, it inserts the method stub with correct formal spec and description.
