### ISSUE TITLE
Subroutine folding is too greedy

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#73]
Testing 1.0.5-beta.1 with legacy INT code whose style is that subroutines are documented in comments immediately above the label.

Before folding:

![image](https://user-images.githubusercontent.com/6726799/98392201-95a42580-204f-11eb-917d-13aed06be4d2.png)

After folding:

![image](https://user-images.githubusercontent.com/6726799/98392322-c08e7980-204f-11eb-909c-1f7349f38ee9.png)

Lines 181 and 191 should not get folded.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Should the whitespace lines like 189 & 190 be folded?

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray Should the whitespace lines like 189 & 190 be folded?

That's debatable. Personally I'm OK with the whitespace lines disappearing in the fold, since they don't really add information in the situation where I'm folding in order to get an overview.

**Comment by isc-bsaviano** [comment]
Ok I will fold the whitespace but not comments that immediately precede routine labels
