### ISSUE TITLE
Problem reported for valid ##class("classname") syntax

### ISSUE THREAD

**Issue by isc-solon** [intersystems/language-server#75]
Quotes are apparently allowed within ##class statements: set person = ##class("Sample.Person").%New()

But VS Code displays "Class '"Sample.Person"' does not exist. InterSystems Language Server [21,22]"

**Comment by isc-bsaviano** [comment]
@isc-solon I just checked this in Studio and I found that using ##class("Sample.Person") isn't supported. For example, I get a compilation error on this line, but wouldn't if I removed the quotes:
`w ##class("%DynamicObject").%New()`

**Comment by isc-solon** [comment]
I knew this would be a weird one. First of all, the syntax you typed above works in Terminal. I don't know why it works, or if it's really supposed to work, but it works. In VS Code, try `w ##class("%Library.DynamicObject").%New()` and you'll see it compiles (which probably means it compiles in Studio also). The only reason I'm pointing this out is that I have a class whose **generated** code contains `##class("classname")` syntax and I noticed that VS Code is flagging it with "class does not exist."

**Comment by isc-bsaviano** [comment]
I just tried `w ##class("%Library.DynamicObject").%New()` in Studio and it compiled. I guess quoted class names are allowed if they are fully qualified. The reason you're getting the "class does not exist" error is that the parser considers the quotes as part of the class name, and I'm not stripping them out. Therefore, it's querying the DB looking for "%Library.DynamicObject".cls, which fails

**Comment by isc-solon** [comment]
I'm checking internally about this syntax and will report back.

**Comment by isc-solon** [comment]
Quoted classnames are valid syntax.
