### ISSUE TITLE
Namespace aware linter

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#77]
Certain tasks require switching namespaces, for example

```
New $namespace
Set $namespace = "%SYS"
Set sc =  ##class(Security.Applications).Modify("/csp/myapp", .props)
// ...
```

Currently the linter marks lines with classes not under the `objectscript.conn.ns` as errors (in this case "Class Security.Applications does not exist). 

It would be nice if the language-server linter was able to deduce the namespace though I understand the difficulty of that. So how about directives such as `// @isc-lint-namespace %SYS` or `//@isc-lint-namespace-push %SYS, @isc-lint-namespace-pop`?

**Comment by isc-bsaviano** [comment]
@mvhenderson We can't deduce the namespace reliably and we do not plan to support custom decorators.

**Comment by mvhenderson** [comment]
@isc-bsaviano so not even a directive like `// @isc-lint-namespace %SYS` we could use to manually assist the linter?

**Comment by isc-jamien** [comment]
If we are going to provide a facility like this then it needs to be carefully thought out and designed as part of a bigger effort, as we don't want to proceed in an adhoc manner. For this particular case I do see the requirement but believe the idea to be fundamentally flawed as, from a conceptual point of view, putting the 'location' of a file within the file itself (even if it is just a hint) is just asking for trouble. However we will bear this requirement in mind going forward

**Comment by isc-kiyer** [comment]
Could we have a setting to disable "Class does not exist" errors altogether in the interim (irrespective of whether or not this feature is implemented)?

**Comment by isc-bsaviano** [comment]
@isc-kiyer You can disable class existence diagnostics already. It's the first configuration setting for the LS extension.
