### ISSUE TITLE
Explorer view should always show what is on the server

### ISSUE THREAD

**Issue by mvhenderson** [intersystems/language-server#78]
Related to #45 and #50 I think.

When browsing the class tree from the Objectscript Explorer VS Code will always show the local exported copy of the file. This leaves no way to see what is actually on the server.  I expected the explorer to be analogous to the Atelier server tab.

Steps to reproduce:

1. export a file
2. modify the file outside VS code (e.g. a `git pull` or fake it using `vi`)
3. browse to the file in the explorer, notice the tooltip is pointing to the working copy and the change is show even though it was never imported and compiled.

**Comment by isc-bsaviano** [comment]
@mvhenderson The ObjectScript Explorer is provided by the main extension and is not modified by the Language Server. Unless I'm misunderstanding you, this issue should be posted to the main extension's repository.

**Comment by mvhenderson** [comment]
OK - I thought this might be an artifact of the language server since I don't recall seeing this before.
