### ISSUE TITLE
Unexpected "Class name is ambiguous" Problem message

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#8]
![Screenshot 2020-10-07 at 13 21 50](https://user-images.githubusercontent.com/6726799/95330335-4fb53f80-08a0-11eb-860f-1a045a2ae57b.png)

The classname lacks a package qualifier, but is preceded by a `#import ClearWater` that provides the package name.

Present in 1.0.0-beta.3

**Comment by isc-bsaviano** [comment]
Included John's fix in version 1.0.0-beta.5.

**Comment by gjsjohnmurray** [comment]
Confirmed fixed.
