### ISSUE TITLE
Incorrect destination go to definition

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#82]
Go to definition offers an incorrect method, and goes to `%DeleteData` instead of `Delete`

![image](https://user-images.githubusercontent.com/1212251/98936781-7c3f2580-24f6-11eb-92ef-2aa771d41a06.png)

**Comment by isc-bsaviano** [comment]
@daimor I was able to reproduce this on 1.0.4 but not my latest beta build of 1.0.5. Can I send you a 1.0.5 beta so you can verify that the bug is fixed there?

**Comment by daimor** [comment]
Yeah, let me try it

**Comment by daimor** [comment]
solved
