### ISSUE TITLE
Support for renaming variables

### ISSUE THREAD

**Issue by daimor** [intersystems/language-server#83]
By F2 on a variable, it should offer a way to rename a variable, and change every occurrence in the code.
It's part of refactoring features, available in VSCode.

**Comment by gjsjohnmurray** [comment]
In other words, be a [RenameProvider](https://code.visualstudio.com/api/references/vscode-api#RenameProvider).

**Comment by isc-bsaviano** [comment]
@daimor @gjsjohnmurray I will add a rename provider that supports renaming for local variables (declared and undelcared) and parameters.

**Comment by daimor** [comment]
Tested in beta, looks good
