### ISSUE TITLE
Be a TypeDefinitionProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#84]
See https://code.visualstudio.com/api/references/vscode-api#TypeDefinitionProvider for how VS Code will use this capability.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Can you explain what you'd expect the behavior to be for type definition requests? Would the behavior be that if you did a type definition request on a declared local variable or typed method argument you'd get taken to the class definition? For example, "go to type definition" on "a" in the method below would take you to %Dictionary.CompiledClass?

```
Method Method2(a As %Dictionary.CompiledClass, b As %String) As %Status [ CodeMode = objectgenerator ]
{
    w a.GeneratedBy
    quit $$$OK
}
```

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano yes, that would be my expectation.

By "declared local variable" I assume you mean one for which a #dim directive exists.

At some point it would be good to extend this to infer the type of a variable assigned from a ##class(Foo.Bar).%New() etc, and even beyond that.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Ok I understand. Yes, by "declared local variable" I mean a local variable that has been #Dim'ed. Adding in type inferencing is a major enhancement that is beyond the scope of this issue so I won't comment on it here.
