### ISSUE TITLE
CSP Runtime Expressions cause colour issue when used on tag attribute

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems/language-server#91]
Moved from https://github.com/intersystems-community/vscode-objectscript/issues/517

**Comment by isc-bsaviano** [comment]
@taulim Can you please post the full text of your test CSP file so I can reproduce your coloring error?

**Comment by Taulim** [comment]
Sure!

```
<html>
	<head>
		<title>test</title>
	</head>
	<body>
		<h1 attr="#(..SomeMethod("test"))#"></h1>

		--

		<h1 attr='#(..SomeMethod("test"))#'></h1>
	</body>
</html>

<script language="cache" method="SomeMethod" arguments="pString">
QUIT pString
</script>
```

**Comment by isc-bsaviano** [comment]
@Taulim What theme are you currently using? InterSystems Default Dark?

**Comment by Taulim** [comment]
At the moment the Dark+ default of vscode.  
I did try switching to the InterSystems Default Dark but the problem seems to still be present.

Also, in case this helps:
- Cache (2018.1.3) is running on Windows 10 (1909)
- Extension set to edit files on the server-side
- VSCode (1.51.1) running on Pop_OS (20.10)

**Comment by isc-bsaviano** [comment]
@Taulim I copied your code into my VSCode using the InterSystems Default Dark theme and I think that there are two issues at play here:

1. VSCode support for semantic tokens is still in a "proposed" state, which leads to some odd behavior when editing files (see #29). This isn't a bug in this extension.
2. The InterSystems Default themes don't explicitly color all tokens currently, so the old TextMate-based coloring from the main extenson is coloring those tokens that were left out ( mainly operators and delimiters, see your first image in the original issue). This is something that can be fixed in this extension and I will open a new enhancement request for it

**Comment by isc-bsaviano** [comment]
Closing this because there are no more actions to be taken

**Comment by Taulim** [comment]
@isc-bsaviano, thank you for the explanation.  
It does indeed makes sense, I have disabled the semantic highlight on vscode and it stop some of the weirdness after the tag but it "breaks" another tag (e.g. csp:include).

**Comment by isc-bsaviano** [comment]
@Taulim Do you want me to take a look at csp:include tag issue? If you paste some example code I can verify that it's not separate issue.

**Comment by Taulim** [comment]
@isc-bsaviano, It is not required for only one tag as it will happen to all the [other](https://cedocs.intersystems.com/latest/csp/docbook/Doc.View.cls?KEY=RCSP_CSPTAGS) csp tags as well.  
It will be a nice improvement for sure in cases where semantic highlight is not helping as much.  

Semantic highlight is really cool, but as you stated before it is still in the proposed state, maybe it will get "better" or have more APIs that can be consumed for edge cases.  

Thank you.

**Comment by isc-bsaviano** [comment]
@Taulim What do you mean by "have more APIs that can be consumed for edge cases"? The Language Server uses the same parsers as Studio so there isn't anything missing

**Comment by Taulim** [comment]
@isc-bsaviano I'm sorry.  
I was not talking about the language-server, I was talking about the vscode's Semantic highlight feature :smile:.

By edge case I meant to have an attribute using double quote to wrap the value and at the same time to be used on a runtime expression.  
For example: `attr="#(..Something("AAA"))#"`, this is not a valid HTML attribute, but it is valid for CSP and the semantic highlight is getting confused.

Unless I misunderstood your previous comment, I'm assuming that is the problem.

**Comment by isc-bsaviano** [comment]
@Taulim I think we're talking about two different things here. The LS's HTML parser can handle that but the vscode-objectscript extension's default coloring probably won't.
