### ISSUE TITLE
Adding comment causes A request has failed error

### ISSUE THREAD

**Issue by bourette** [intersystems/language-server#93]
Issue Type: <b>Bug</b>

Update a method inserting new line tab//m( causes A request has failed. See the output for more information

Extension version: 1.0.5
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

**Comment by isc-bsaviano** [comment]
@bourette Can you turn your trace on and let me know what request failed and the error message given?

**Comment by isc-bsaviano** [comment]
@bourette Never mind, I was just able to reproduce it. It's a SignatureHelp request. I'll fix my logic so it doesn't try to compute SignatureHelp info when the `(` is in a comment
