### ISSUE TITLE
Bug: Include files with '.' in the name are parsed incorrectly when referenced from another include file

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/language-server#99]
If you have an include file and reference another include file using #include, you should be able to use the "Go to definition" to open the referenced include file. This works if the referenced include file has no '.' in it. However, if it does have a '.' then it is not parsed correctly and the "Go to definition" does not work. Here is what the parsing looks for an include file with no '.' vs one with a '.':

<img width="194" alt=" 2020-12-10 at 16 11 09" src="https://user-images.githubusercontent.com/75783557/101761582-565f6d80-3b02-11eb-8402-1fbfbb63fafd.png">

As you can see in the above example, %ZHS.OAuth2 should be parsed as one name. Note that this works fine when referencing the same include file from a class. It is only an issue when referencing it from another include file.

I am using v1.0.5 on a Mac.

**Comment by isc-bsaviano** [comment]
@isc-AndrewCheshire  The second part of the routine name (including the ".") isn't being assigned any token. It should be COS_Routine
